# -----------------------------------------------------------------------------
#  File:        analyzerlib.py
#  Description: Analyzer for ntuples created by TheNtupleMaker
#  Created:     Thu May 30 15:41:56 2013 by mkntanalyzer.py
#  Author:      Daniele Marconi
# -----------------------------------------------------------------------------
from ROOT import *
from time import sleep
from string import *
from array import array
from math import *
from sys import exit
import os, sys, re
# -----------------------------------------------------------------------------
STANDALONE = True  # set to False to work within CMSSW
if STANDALONE:
    gROOT.ProcessLine(".L treestream.cc+")
    gROOT.ProcessLine(".L pdg.cc+")
else:
    from PhysicsTools.TheNtupleMaker.AutoLoader import *
# -----------------------------------------------------------------------------
# -- Classes, procedures and functions
# -----------------------------------------------------------------------------
class outputFile:

    def __init__(self, filename, stream=None, savecount=50000):
		if stream != None:
		    print "events will be skimmed to file", filename
		    self.tree = stream.tree().CloneTree(0)
			self.weight = Double()
			self.b_weight = self.tree.Branch("eventWeight", self.weight,
											 "eventWeight/D")
			self.SAVECOUNT = savecount
		else:
			self.tree = None
			self.b_weight = None

		self.entry = 0
			
		self.filename = filename
		self.file = TFile(filename, "recreate")

		self.hist = TH1F("counts", "", 1, 0, 1)
		self.hist.SetBit(TH1.kCanRebin)
		self.hist.SetStats(0)

		self.b_weight = 0

	def addEvent(self, weight=1.0):
		if self.tree == None: return
		
		self.file = self.tree.GetCurrentFile()
		self.file.cd()
		self.tree.Fill()

		self.entry += 1		
		if self.entry % self.SAVECOUNT == 0:
			self.tree.AutoSave("SaveSelf")
				
	def count(self, cond, w=1):
		self.hist.Fill(cond, w)
		
	def close(self):
		print "==> histograms saved to file", self.filename
		if self.tree != None:			
			print "==> events skimmed to file", self.filename
			self.file = self.tree.GetCurrentFile()
			
		self.file.cd()
		#self.file.Write("", TObject.kOverwrite)
		self.file.Write()
		self.file.ls()
		self.file.Close()
# -----------------------------------------------------------------------------
class commandLine:
	def __init__(self):
		pass

def decodeCommandLine():
	argv = sys.argv
	argc = len(argv)

	cl = commandLine()
	cl.progname = split(os.path.basename(argv[0]),'.')[0]

	if argc > 1:
		cl.filelist = argv[1]
	else:
		cl.filelist = "filelist.txt"

	if argc > 2: 
		cl.outputfilename = argv[2] # 2nd (optional) command line argument
	else:
		cl.outputfilename = cl.progname + "_histograms"

	# Make sure extension is ".root"
	if cl.outputfilename[:-5] != ".root": cl.outputfilename += ".root"
	print "==> output to:", cl.outputfilename

	return cl
# -----------------------------------------------------------------------------
def error(message):
	print "** error ** " + message
	sys.exit(0)
# -----------------------------------------------------------------------------
#  Read ntuple filenames from file list

def getFilenames(filelist):
	if not os.path.exists(filelist):
		error("unable to open file: " + filelist)

	# Get ntuple file names
	filenames = filter(lambda x: x != "",
					   map(strip, open(filelist).readlines()))
	v = vector("string")()
	for filename in filenames: v.push_back(filename)
	return v
# -----------------------------------------------------------------------------
TEXTFONT = 42
TEXTSIZE = 0.031
#------------------------------------------------------------------------------
def setStyle():
	gROOT.SetStyle("Pub")
	style = gROOT.GetStyle("Pub")
	style.SetPalette(1)
	
	# For the canvas
	style.SetCanvasBorderMode(0)
	style.SetCanvasColor(kWhite)
	style.SetCanvasDefH(500)
	style.SetCanvasDefW(500)
	style.SetCanvasDefX(0)
	style.SetCanvasDefY(0)

	# For the pad
	style.SetPadBorderMode(0)
	style.SetPadColor(kWhite)
	style.SetPadGridX(kFALSE)
	style.SetPadGridY(kTRUE)
	style.SetGridColor(kGreen)
	style.SetGridStyle(3)
	style.SetGridWidth(1)

	# For the frame
	style.SetFrameBorderMode(0)
	style.SetFrameBorderSize(1)
	style.SetFrameFillColor(0)
	style.SetFrameFillStyle(0)
	style.SetFrameLineColor(1)
	style.SetFrameLineStyle(1)
	style.SetFrameLineWidth(1)

	# For the histogram
	style.SetHistLineColor(1)
	style.SetHistLineStyle(0)
	style.SetHistLineWidth(1)
	style.SetEndErrorSize(2)
	style.SetErrorX(0.)
	style.SetMarkerSize(0.1)
	style.SetMarkerStyle(20)

	# For the fit/function
	style.SetOptFit(1)
	style.SetFitFormat("5.4g")
	style.SetFuncColor(2)
	style.SetFuncStyle(1)
	style.SetFuncWidth(1)

	#For the date
	style.SetOptDate(0)

	# For the statistics box
	style.SetOptFile(0)
	style.SetOptStat("")
	# To display the mean and RMS
	#style.SetOptStat("mr") 
	style.SetStatColor(kWhite)
	style.SetStatFont(TEXTFONT)
	style.SetStatFontSize(TEXTSIZE)
	style.SetStatTextColor(1)
	style.SetStatFormat("6.4g")
	style.SetStatBorderSize(1)
	style.SetStatH(0.2)
	style.SetStatW(0.3)

	# Margins
	style.SetPadTopMargin(0.05)
	style.SetPadBottomMargin(0.16)
	style.SetPadLeftMargin(0.16)
	style.SetPadRightMargin(0.16)

	# For the global title
	style.SetOptTitle(0)
	style.SetTitleFont(TEXTFONT)
	style.SetTitleColor(1)
	style.SetTitleTextColor(1)
	style.SetTitleFillColor(10)
	style.SetTitleFontSize(TEXTSIZE*1.1)

	# For the axis titles
	style.SetTitleColor(1, "XYZ")
	style.SetTitleFont(TEXTFONT, "XYZ")
	style.SetTitleSize(TEXTSIZE*1.2, "XYZ") # 0,05
	style.SetTitleXOffset(1.25) # 0.9
	style.SetTitleYOffset(1.25) # 1.25

	# For the axis labels
	style.SetLabelColor(1, "XYZ")
	style.SetLabelFont(TEXTFONT, "XYZ")
	style.SetLabelOffset(0.006, "XYZ")
	style.SetLabelSize(TEXTSIZE*1.2, "XYZ")

	# For the axis
	style.SetAxisColor(1, "XYZ")
	style.SetStripDecimals(kTRUE)
	style.SetTickLength(0.03, "XYZ")
	style.SetNdivisions(505, "XYZ")

	# To get tick marks on the opposite side of the frame
	style.SetPadTickX(1)  
	style.SetPadTickY(1)

	# Change for log plots
	style.SetOptLogx(0)
	style.SetOptLogy(0)
	style.SetOptLogz(0)

	# Postscript options
	style.SetPaperSize(20.,20.)

	style.cd()
# -----------------------------------------------------------------------------
#  Define variables to be read
# -----------------------------------------------------------------------------
cmdline = decodeCommandLine()

#  Get names of ntuple files to be processed and open chain of ntuples

filenames = getFilenames(cmdline.filelist)
stream = itreestream(filenames, "Events")
if not stream.good(): error("unable to open ntuple file(s)")

beamspot_x0	= Double()
beamspot_y0	= Double()
beamspot_z0	= Double()
electron_deltaEtaSuperClusterTrackAtVtx	= vector("float")(200)
electron_deltaPhiSuperClusterTrackAtVtx	= vector("float")(200)
electron_dr04EcalRecHitSumEt	= vector("float")(200)
electron_dr04TkSumPt	= vector("float")(200)
electron_eSuperClusterOverP	= vector("float")(200)
electron_energy	= vector("double")(200)
electron_et	= vector("double")(200)
electron_eta	= vector("double")(200)
electron_gsfTrack_d0	= vector("double")(200)
electron_gsfTrack_dxy	= vector("double")(200)
electron_gsfTrack_dz	= vector("double")(200)
electron_hadronicOverEm	= vector("float")(200)
electron_p	= vector("double")(200)
electron_phi	= vector("double")(200)
electron_pt	= vector("double")(200)
electron_px	= vector("double")(200)
electron_py	= vector("double")(200)
electron_pz	= vector("double")(200)
electron_scE1x5	= vector("float")(200)
electron_scE2x5Max	= vector("float")(200)
electron_scE5x5	= vector("float")(200)
electron_sigmaIetaIeta	= vector("float")(200)
eventhelper_bunchCrossing	= Long()
eventhelper_event	= Long()
eventhelper_isRealData	= Long()
eventhelper_luminosityBlock	= Long()
eventhelper_orbitNumber	= Long()
eventhelper_run	= Long()
genparticlehelper_charge	= vector("int")(500)
genparticlehelper_eta	= vector("double")(500)
genparticlehelper_firstDaughter	= vector("int")(500)
genparticlehelper_firstMother	= vector("int")(500)
genparticlehelper_lastDaughter	= vector("int")(500)
genparticlehelper_lastMother	= vector("int")(500)
genparticlehelper_mass	= vector("double")(500)
genparticlehelper_pdgId	= vector("int")(500)
genparticlehelper_phi	= vector("double")(500)
genparticlehelper_pt	= vector("double")(500)
genparticlehelper_status	= vector("int")(500)
genruninfoproduct_crossSection	= Double()
genruninfoproduct_filterEfficiency	= Double()
genruninfoproduct_internalXSec_value	= Double()
gsfelectron_deltaEtaSuperClusterTrackAtVtx	= vector("float")(200)
gsfelectron_deltaPhiSuperClusterTrackAtVtx	= vector("float")(200)
gsfelectron_dr04EcalRecHitSumEt	= vector("float")(200)
gsfelectron_dr04TkSumPt	= vector("float")(200)
gsfelectron_eSuperClusterOverP	= vector("float")(200)
gsfelectron_energy	= vector("double")(200)
gsfelectron_et	= vector("double")(200)
gsfelectron_eta	= vector("double")(200)
gsfelectron_gsfTrack_d0	= vector("double")(200)
gsfelectron_gsfTrack_dxy	= vector("double")(200)
gsfelectron_gsfTrack_dz	= vector("double")(200)
gsfelectron_hadronicOverEm	= vector("float")(200)
gsfelectron_p	= vector("double")(200)
gsfelectron_phi	= vector("double")(200)
gsfelectron_pt	= vector("double")(200)
gsfelectron_px	= vector("double")(200)
gsfelectron_py	= vector("double")(200)
gsfelectron_pz	= vector("double")(200)
gsfelectron_scE1x5	= vector("float")(200)
gsfelectron_scE2x5Max	= vector("float")(200)
gsfelectron_scE5x5	= vector("float")(200)
gsfelectron_sigmaIetaIeta	= vector("float")(200)
jet_HFEMEnergy	= vector("float")(200)
jet_HFEMEnergyFraction	= vector("float")(200)
jet_HFEMMultiplicity	= vector("int")(200)
jet_HFHadronEnergy	= vector("float")(200)
jet_HFHadronEnergyFraction	= vector("float")(200)
jet_HFHadronMultiplicity	= vector("int")(200)
jet_bDiscriminator_combinedInclusiveSecondaryVertexBJetTags	= vector("float")(200)
jet_bDiscriminator_combinedMVABJetTags	= vector("float")(200)
jet_bDiscriminator_combinedSecondaryVertexBJetTags	= vector("float")(200)
jet_bDiscriminator_combinedSecondaryVertexMVABJetTags	= vector("float")(200)
jet_bDiscriminator_impactParameterTagInfos	= vector("float")(200)
jet_bDiscriminator_inclusiveSecondaryVertexFinderTagInfos	= vector("float")(200)
jet_bDiscriminator_jetBProbabilityBJetTags	= vector("float")(200)
jet_bDiscriminator_jetProbabilityBJetTags	= vector("float")(200)
jet_bDiscriminator_negativeTrackCountingHighEffJetTags	= vector("float")(200)
jet_bDiscriminator_negativeTrackCountingHighPurJetTags	= vector("float")(200)
jet_bDiscriminator_secondaryVertexNegativeTagInfos	= vector("float")(200)
jet_bDiscriminator_secondaryVertexTagInfos	= vector("float")(200)
jet_bDiscriminator_simpleSecondaryVertexHighEffBJetTags	= vector("float")(200)
jet_bDiscriminator_simpleSecondaryVertexHighPurBJetTags	= vector("float")(200)
jet_bDiscriminator_simpleSecondaryVertexNegativeHighEffBJetTags	= vector("float")(200)
jet_bDiscriminator_simpleSecondaryVertexNegativeHighPurBJetTags	= vector("float")(200)
jet_bDiscriminator_softElectronTagInfos	= vector("float")(200)
jet_bDiscriminator_softMuonBJetTags	= vector("float")(200)
jet_bDiscriminator_softMuonByIP3dBJetTags	= vector("float")(200)
jet_bDiscriminator_softMuonByPtBJetTags	= vector("float")(200)
jet_bDiscriminator_softMuonTagInfos	= vector("float")(200)
jet_bDiscriminator_trackCountingHighEffBJetTags	= vector("float")(200)
jet_bDiscriminator_trackCountingHighPurBJetTags	= vector("float")(200)
jet_charge	= vector("int")(200)
jet_chargedEmEnergyFraction	= vector("float")(200)
jet_chargedHadronEnergyFraction	= vector("float")(200)
jet_chargedHadronMultiplicity	= vector("int")(200)
jet_electronEnergy	= vector("float")(200)
jet_electronEnergyFraction	= vector("float")(200)
jet_electronMultiplicity	= vector("int")(200)
jet_energy	= vector("double")(200)
jet_et	= vector("double")(200)
jet_eta	= vector("double")(200)
jet_muonEnergy	= vector("float")(200)
jet_muonEnergyFraction	= vector("float")(200)
jet_neutralEmEnergyFraction	= vector("float")(200)
jet_neutralHadronEnergy	= vector("float")(200)
jet_neutralHadronEnergyFraction	= vector("float")(200)
jet_neutralHadronMultiplicity	= vector("int")(200)
jet_numberOfDaughters	= vector("size_t")(200)
jet_p	= vector("double")(200)
jet_phi	= vector("double")(200)
jet_photonEnergy	= vector("float")(200)
jet_photonEnergyFraction	= vector("float")(200)
jet_photonMultiplicity	= vector("int")(200)
jet_pt	= vector("double")(200)
jet_px	= vector("double")(200)
jet_py	= vector("double")(200)
jet_pz	= vector("double")(200)
met_energy	= vector("double")(200)
met_et	= vector("double")(200)
met_eta	= vector("double")(200)
met_p	= vector("double")(200)
met_phi	= vector("double")(200)
met_pt	= vector("double")(200)
met_px	= vector("double")(200)
met_py	= vector("double")(200)
met_pz	= vector("double")(200)
muon_energy	= vector("double")(200)
muon_et	= vector("double")(200)
muon_eta	= vector("double")(200)
muon_globalTrack_hitPattern_numberOfValidMuonHits	= vector("int")(200)
muon_globalTrack_normalizedChi2	= vector("double")(200)
muon_innerTrack_dxy	= vector("double")(200)
muon_innerTrack_dz	= vector("double")(200)
muon_innerTrack_hitPattern_numberOfValidPixelHits	= vector("int")(200)
muon_innerTrack_hitPattern_pixelLayersWithMeasurement	= vector("int")(200)
muon_innerTrack_normalizedChi2	= vector("double")(200)
muon_isGlobalMuon	= vector("int")(200)
muon_isPFMuon	= vector("int")(200)
muon_isTrackerMuon	= vector("int")(200)
muon_muonBestTrack_dxy	= vector("double")(200)
muon_muonBestTrack_dz	= vector("double")(200)
muon_numberOfMatchedStations	= vector("int")(200)
muon_p	= vector("double")(200)
muon_pfIsolationR03_sumChargedHadronPt	= vector("float")(200)
muon_pfIsolationR03_sumChargedParticlePt	= vector("float")(200)
muon_pfIsolationR03_sumNeutralHadronEt	= vector("float")(200)
muon_pfIsolationR03_sumNeutralHadronEtHighThreshold	= vector("float")(200)
muon_pfIsolationR03_sumPUPt	= vector("float")(200)
muon_pfIsolationR03_sumPhotonEt	= vector("float")(200)
muon_pfIsolationR03_sumPhotonEtHighThreshold	= vector("float")(200)
muon_pfIsolationR04_sumChargedHadronPt	= vector("float")(200)
muon_pfIsolationR04_sumChargedParticlePt	= vector("float")(200)
muon_pfIsolationR04_sumNeutralHadronEt	= vector("float")(200)
muon_pfIsolationR04_sumNeutralHadronEtHighThreshold	= vector("float")(200)
muon_pfIsolationR04_sumPUPt	= vector("float")(200)
muon_pfIsolationR04_sumPhotonEt	= vector("float")(200)
muon_pfIsolationR04_sumPhotonEtHighThreshold	= vector("float")(200)
muon_phi	= vector("double")(200)
muon_pt	= vector("double")(200)
muon_px	= vector("double")(200)
muon_py	= vector("double")(200)
muon_pz	= vector("double")(200)
nelectron	= Long()
ngenparticlehelper	= Long()
ngsfelectron	= Long()
njet	= Long()
nmet	= Long()
nmuon	= Long()
npfmet	= Long()
npfmet2	= Long()
npileupsummaryinfo	= Long()
ntauhelper	= Long()
nvertex	= Long()
pfmet2_energy	= vector("double")(200)
pfmet2_et	= vector("double")(200)
pfmet2_eta	= vector("double")(200)
pfmet2_p	= vector("double")(200)
pfmet2_phi	= vector("double")(200)
pfmet2_pt	= vector("double")(200)
pfmet2_px	= vector("double")(200)
pfmet2_py	= vector("double")(200)
pfmet2_pz	= vector("double")(200)
pfmet_energy	= vector("double")(200)
pfmet_et	= vector("double")(200)
pfmet_eta	= vector("double")(200)
pfmet_p	= vector("double")(200)
pfmet_phi	= vector("double")(200)
pfmet_pt	= vector("double")(200)
pfmet_px	= vector("double")(200)
pfmet_py	= vector("double")(200)
pfmet_pz	= vector("double")(200)
pileupsummaryinfo_getBunchCrossing	= vector("int")(10)
pileupsummaryinfo_getPU_NumInteractions	= vector("int")(10)
tauhelper_charge	= vector("int")(200)
tauhelper_energy	= vector("double")(200)
tauhelper_et	= vector("double")(200)
tauhelper_eta	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_energy	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_et	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_eta	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_mass	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_massSqr	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_mt	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_mtSqr	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_p	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_phi	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_pt	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_px	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_py	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_pz	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_rapidity	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_theta	= vector("double")(200)
tauhelper_leadPFChargedHadrCand_y	= vector("double")(200)
tauhelper_p	= vector("double")(200)
tauhelper_phi	= vector("double")(200)
tauhelper_pt	= vector("double")(200)
tauhelper_px	= vector("double")(200)
tauhelper_py	= vector("double")(200)
tauhelper_pz	= vector("double")(200)
tauhelper_signalPFChargedHadrCands_size	= vector("size_t")(200)
tauhelper_tauID_againstElectronDeadECAL	= vector("float")(200)
tauhelper_tauID_againstElectronLoose	= vector("float")(200)
tauhelper_tauID_againstElectronLooseMVA2	= vector("float")(200)
tauhelper_tauID_againstElectronLooseMVA3	= vector("float")(200)
tauhelper_tauID_againstElectronMVA	= vector("float")(200)
tauhelper_tauID_againstElectronMVA2category	= vector("float")(200)
tauhelper_tauID_againstElectronMVA2raw	= vector("float")(200)
tauhelper_tauID_againstElectronMVA3category	= vector("float")(200)
tauhelper_tauID_againstElectronMVA3raw	= vector("float")(200)
tauhelper_tauID_againstElectronMedium	= vector("float")(200)
tauhelper_tauID_againstElectronMediumMVA2	= vector("float")(200)
tauhelper_tauID_againstElectronMediumMVA3	= vector("float")(200)
tauhelper_tauID_againstElectronTight	= vector("float")(200)
tauhelper_tauID_againstElectronTightMVA2	= vector("float")(200)
tauhelper_tauID_againstElectronTightMVA3	= vector("float")(200)
tauhelper_tauID_againstElectronVLooseMVA2	= vector("float")(200)
tauhelper_tauID_againstElectronVTightMVA3	= vector("float")(200)
tauhelper_tauID_againstMuonLoose	= vector("float")(200)
tauhelper_tauID_againstMuonLoose2	= vector("float")(200)
tauhelper_tauID_againstMuonMedium	= vector("float")(200)
tauhelper_tauID_againstMuonMedium2	= vector("float")(200)
tauhelper_tauID_againstMuonTight	= vector("float")(200)
tauhelper_tauID_againstMuonTight2	= vector("float")(200)
tauhelper_tauID_byCombinedIsolationDeltaBetaCorrRaw	= vector("float")(200)
tauhelper_tauID_byCombinedIsolationDeltaBetaCorrRaw3Hits	= vector("float")(200)
tauhelper_tauID_byIsolationMVA2raw	= vector("float")(200)
tauhelper_tauID_byIsolationMVAraw	= vector("float")(200)
tauhelper_tauID_byLooseCombinedIsolationDeltaBetaCorr	= vector("float")(200)
tauhelper_tauID_byLooseCombinedIsolationDeltaBetaCorr3Hits	= vector("float")(200)
tauhelper_tauID_byLooseIsolation	= vector("float")(200)
tauhelper_tauID_byLooseIsolationDeltaBetaCorr	= vector("float")(200)
tauhelper_tauID_byLooseIsolationMVA	= vector("float")(200)
tauhelper_tauID_byLooseIsolationMVA2	= vector("float")(200)
tauhelper_tauID_byMediumCombinedIsolationDeltaBetaCorr	= vector("float")(200)
tauhelper_tauID_byMediumCombinedIsolationDeltaBetaCorr3Hits	= vector("float")(200)
tauhelper_tauID_byMediumIsolation	= vector("float")(200)
tauhelper_tauID_byMediumIsolationDeltaBetaCorr	= vector("float")(200)
tauhelper_tauID_byMediumIsolationMVA	= vector("float")(200)
tauhelper_tauID_byMediumIsolationMVA2	= vector("float")(200)
tauhelper_tauID_byTightCombinedIsolationDeltaBetaCorr	= vector("float")(200)
tauhelper_tauID_byTightCombinedIsolationDeltaBetaCorr3Hits	= vector("float")(200)
tauhelper_tauID_byTightIsolation	= vector("float")(200)
tauhelper_tauID_byTightIsolationDeltaBetaCorr	= vector("float")(200)
tauhelper_tauID_byTightIsolationMVA	= vector("float")(200)
tauhelper_tauID_byTightIsolationMVA2	= vector("float")(200)
tauhelper_tauID_byVLooseCombinedIsolationDeltaBetaCorr	= vector("float")(200)
tauhelper_tauID_byVLooseIsolation	= vector("float")(200)
tauhelper_tauID_byVLooseIsolationDeltaBetaCorr	= vector("float")(200)
tauhelper_tauID_decayModeFinding	= vector("float")(200)
triggerresultshelper_prescale_HLT_DoubleMediumIsoPFTau35_Trk5_eta2p1_v6	= Long()
triggerresultshelper_value_HLT_DoubleMediumIsoPFTau35_Trk5_eta2p1_v6	= Long()
vertex_isFake	= vector("int")(200)
vertex_ndof	= vector("double")(200)
vertex_x	= vector("double")(200)
vertex_y	= vector("double")(200)
vertex_z	= vector("double")(200)

stream.select("recoBeamSpot_offlineBeamSpot.x0", beamspot_x0)
stream.select("recoBeamSpot_offlineBeamSpot.y0", beamspot_y0)
stream.select("recoBeamSpot_offlineBeamSpot.z0", beamspot_z0)
stream.select("patElectron_patElectrons.deltaEtaSuperClusterTrackAtVtx", electron_deltaEtaSuperClusterTrackAtVtx)
stream.select("patElectron_patElectrons.deltaPhiSuperClusterTrackAtVtx", electron_deltaPhiSuperClusterTrackAtVtx)
stream.select("patElectron_patElectrons.dr04EcalRecHitSumEt", electron_dr04EcalRecHitSumEt)
stream.select("patElectron_patElectrons.dr04TkSumPt", electron_dr04TkSumPt)
stream.select("patElectron_patElectrons.eSuperClusterOverP", electron_eSuperClusterOverP)
stream.select("patElectron_patElectrons.energy", electron_energy)
stream.select("patElectron_patElectrons.et", electron_et)
stream.select("patElectron_patElectrons.eta", electron_eta)
stream.select("patElectron_patElectrons.gsfTrack_d0", electron_gsfTrack_d0)
stream.select("patElectron_patElectrons.gsfTrack_dxy", electron_gsfTrack_dxy)
stream.select("patElectron_patElectrons.gsfTrack_dz", electron_gsfTrack_dz)
stream.select("patElectron_patElectrons.hadronicOverEm", electron_hadronicOverEm)
stream.select("patElectron_patElectrons.p", electron_p)
stream.select("patElectron_patElectrons.phi", electron_phi)
stream.select("patElectron_patElectrons.pt", electron_pt)
stream.select("patElectron_patElectrons.px", electron_px)
stream.select("patElectron_patElectrons.py", electron_py)
stream.select("patElectron_patElectrons.pz", electron_pz)
stream.select("patElectron_patElectrons.scE1x5", electron_scE1x5)
stream.select("patElectron_patElectrons.scE2x5Max", electron_scE2x5Max)
stream.select("patElectron_patElectrons.scE5x5", electron_scE5x5)
stream.select("patElectron_patElectrons.sigmaIetaIeta", electron_sigmaIetaIeta)
stream.select("edmEventHelper_info.bunchCrossing", eventhelper_bunchCrossing)
stream.select("edmEventHelper_info.event", eventhelper_event)
stream.select("edmEventHelper_info.isRealData", eventhelper_isRealData)
stream.select("edmEventHelper_info.luminosityBlock", eventhelper_luminosityBlock)
stream.select("edmEventHelper_info.orbitNumber", eventhelper_orbitNumber)
stream.select("edmEventHelper_info.run", eventhelper_run)
stream.select("recoGenParticleHelper_genParticles.charge", genparticlehelper_charge)
stream.select("recoGenParticleHelper_genParticles.eta", genparticlehelper_eta)
stream.select("recoGenParticleHelper_genParticles.firstDaughter", genparticlehelper_firstDaughter)
stream.select("recoGenParticleHelper_genParticles.firstMother", genparticlehelper_firstMother)
stream.select("recoGenParticleHelper_genParticles.lastDaughter", genparticlehelper_lastDaughter)
stream.select("recoGenParticleHelper_genParticles.lastMother", genparticlehelper_lastMother)
stream.select("recoGenParticleHelper_genParticles.mass", genparticlehelper_mass)
stream.select("recoGenParticleHelper_genParticles.pdgId", genparticlehelper_pdgId)
stream.select("recoGenParticleHelper_genParticles.phi", genparticlehelper_phi)
stream.select("recoGenParticleHelper_genParticles.pt", genparticlehelper_pt)
stream.select("recoGenParticleHelper_genParticles.status", genparticlehelper_status)
stream.select("GenRunInfoProduct_generator.crossSection", genruninfoproduct_crossSection)
stream.select("GenRunInfoProduct_generator.filterEfficiency", genruninfoproduct_filterEfficiency)
stream.select("GenRunInfoProduct_generator.internalXSec_value", genruninfoproduct_internalXSec_value)
stream.select("recoGsfElectron_gsfElectrons.deltaEtaSuperClusterTrackAtVtx", gsfelectron_deltaEtaSuperClusterTrackAtVtx)
stream.select("recoGsfElectron_gsfElectrons.deltaPhiSuperClusterTrackAtVtx", gsfelectron_deltaPhiSuperClusterTrackAtVtx)
stream.select("recoGsfElectron_gsfElectrons.dr04EcalRecHitSumEt", gsfelectron_dr04EcalRecHitSumEt)
stream.select("recoGsfElectron_gsfElectrons.dr04TkSumPt", gsfelectron_dr04TkSumPt)
stream.select("recoGsfElectron_gsfElectrons.eSuperClusterOverP", gsfelectron_eSuperClusterOverP)
stream.select("recoGsfElectron_gsfElectrons.energy", gsfelectron_energy)
stream.select("recoGsfElectron_gsfElectrons.et", gsfelectron_et)
stream.select("recoGsfElectron_gsfElectrons.eta", gsfelectron_eta)
stream.select("recoGsfElectron_gsfElectrons.gsfTrack_d0", gsfelectron_gsfTrack_d0)
stream.select("recoGsfElectron_gsfElectrons.gsfTrack_dxy", gsfelectron_gsfTrack_dxy)
stream.select("recoGsfElectron_gsfElectrons.gsfTrack_dz", gsfelectron_gsfTrack_dz)
stream.select("recoGsfElectron_gsfElectrons.hadronicOverEm", gsfelectron_hadronicOverEm)
stream.select("recoGsfElectron_gsfElectrons.p", gsfelectron_p)
stream.select("recoGsfElectron_gsfElectrons.phi", gsfelectron_phi)
stream.select("recoGsfElectron_gsfElectrons.pt", gsfelectron_pt)
stream.select("recoGsfElectron_gsfElectrons.px", gsfelectron_px)
stream.select("recoGsfElectron_gsfElectrons.py", gsfelectron_py)
stream.select("recoGsfElectron_gsfElectrons.pz", gsfelectron_pz)
stream.select("recoGsfElectron_gsfElectrons.scE1x5", gsfelectron_scE1x5)
stream.select("recoGsfElectron_gsfElectrons.scE2x5Max", gsfelectron_scE2x5Max)
stream.select("recoGsfElectron_gsfElectrons.scE5x5", gsfelectron_scE5x5)
stream.select("recoGsfElectron_gsfElectrons.sigmaIetaIeta", gsfelectron_sigmaIetaIeta)
stream.select("patJet_selectedPatJets.HFEMEnergy", jet_HFEMEnergy)
stream.select("patJet_selectedPatJets.HFEMEnergyFraction", jet_HFEMEnergyFraction)
stream.select("patJet_selectedPatJets.HFEMMultiplicity", jet_HFEMMultiplicity)
stream.select("patJet_selectedPatJets.HFHadronEnergy", jet_HFHadronEnergy)
stream.select("patJet_selectedPatJets.HFHadronEnergyFraction", jet_HFHadronEnergyFraction)
stream.select("patJet_selectedPatJets.HFHadronMultiplicity", jet_HFHadronMultiplicity)
stream.select("patJet_selectedPatJets.bDiscriminator_combinedInclusiveSecondaryVertexBJetTags", jet_bDiscriminator_combinedInclusiveSecondaryVertexBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_combinedMVABJetTags", jet_bDiscriminator_combinedMVABJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_combinedSecondaryVertexBJetTags", jet_bDiscriminator_combinedSecondaryVertexBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_combinedSecondaryVertexMVABJetTags", jet_bDiscriminator_combinedSecondaryVertexMVABJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_impactParameterTagInfos", jet_bDiscriminator_impactParameterTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_inclusiveSecondaryVertexFinderTagInfos", jet_bDiscriminator_inclusiveSecondaryVertexFinderTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_jetBProbabilityBJetTags", jet_bDiscriminator_jetBProbabilityBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_jetProbabilityBJetTags", jet_bDiscriminator_jetProbabilityBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_negativeTrackCountingHighEffJetTags", jet_bDiscriminator_negativeTrackCountingHighEffJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_negativeTrackCountingHighPurJetTags", jet_bDiscriminator_negativeTrackCountingHighPurJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_secondaryVertexNegativeTagInfos", jet_bDiscriminator_secondaryVertexNegativeTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_secondaryVertexTagInfos", jet_bDiscriminator_secondaryVertexTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_simpleSecondaryVertexHighEffBJetTags", jet_bDiscriminator_simpleSecondaryVertexHighEffBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_simpleSecondaryVertexHighPurBJetTags", jet_bDiscriminator_simpleSecondaryVertexHighPurBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_simpleSecondaryVertexNegativeHighEffBJetTags", jet_bDiscriminator_simpleSecondaryVertexNegativeHighEffBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_simpleSecondaryVertexNegativeHighPurBJetTags", jet_bDiscriminator_simpleSecondaryVertexNegativeHighPurBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_softElectronTagInfos", jet_bDiscriminator_softElectronTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_softMuonBJetTags", jet_bDiscriminator_softMuonBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_softMuonByIP3dBJetTags", jet_bDiscriminator_softMuonByIP3dBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_softMuonByPtBJetTags", jet_bDiscriminator_softMuonByPtBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_softMuonTagInfos", jet_bDiscriminator_softMuonTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_trackCountingHighEffBJetTags", jet_bDiscriminator_trackCountingHighEffBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_trackCountingHighPurBJetTags", jet_bDiscriminator_trackCountingHighPurBJetTags)
stream.select("patJet_selectedPatJets.charge", jet_charge)
stream.select("patJet_selectedPatJets.chargedEmEnergyFraction", jet_chargedEmEnergyFraction)
stream.select("patJet_selectedPatJets.chargedHadronEnergyFraction", jet_chargedHadronEnergyFraction)
stream.select("patJet_selectedPatJets.chargedHadronMultiplicity", jet_chargedHadronMultiplicity)
stream.select("patJet_selectedPatJets.electronEnergy", jet_electronEnergy)
stream.select("patJet_selectedPatJets.electronEnergyFraction", jet_electronEnergyFraction)
stream.select("patJet_selectedPatJets.electronMultiplicity", jet_electronMultiplicity)
stream.select("patJet_selectedPatJets.energy", jet_energy)
stream.select("patJet_selectedPatJets.et", jet_et)
stream.select("patJet_selectedPatJets.eta", jet_eta)
stream.select("patJet_selectedPatJets.muonEnergy", jet_muonEnergy)
stream.select("patJet_selectedPatJets.muonEnergyFraction", jet_muonEnergyFraction)
stream.select("patJet_selectedPatJets.neutralEmEnergyFraction", jet_neutralEmEnergyFraction)
stream.select("patJet_selectedPatJets.neutralHadronEnergy", jet_neutralHadronEnergy)
stream.select("patJet_selectedPatJets.neutralHadronEnergyFraction", jet_neutralHadronEnergyFraction)
stream.select("patJet_selectedPatJets.neutralHadronMultiplicity", jet_neutralHadronMultiplicity)
stream.select("patJet_selectedPatJets.numberOfDaughters", jet_numberOfDaughters)
stream.select("patJet_selectedPatJets.p", jet_p)
stream.select("patJet_selectedPatJets.phi", jet_phi)
stream.select("patJet_selectedPatJets.photonEnergy", jet_photonEnergy)
stream.select("patJet_selectedPatJets.photonEnergyFraction", jet_photonEnergyFraction)
stream.select("patJet_selectedPatJets.photonMultiplicity", jet_photonMultiplicity)
stream.select("patJet_selectedPatJets.pt", jet_pt)
stream.select("patJet_selectedPatJets.px", jet_px)
stream.select("patJet_selectedPatJets.py", jet_py)
stream.select("patJet_selectedPatJets.pz", jet_pz)
stream.select("patMET_patMETs.energy", met_energy)
stream.select("patMET_patMETs.et", met_et)
stream.select("patMET_patMETs.eta", met_eta)
stream.select("patMET_patMETs.p", met_p)
stream.select("patMET_patMETs.phi", met_phi)
stream.select("patMET_patMETs.pt", met_pt)
stream.select("patMET_patMETs.px", met_px)
stream.select("patMET_patMETs.py", met_py)
stream.select("patMET_patMETs.pz", met_pz)
stream.select("patMuon_patMuons.energy", muon_energy)
stream.select("patMuon_patMuons.et", muon_et)
stream.select("patMuon_patMuons.eta", muon_eta)
stream.select("patMuon_patMuons.globalTrack_hitPattern_numberOfValidMuonHits", muon_globalTrack_hitPattern_numberOfValidMuonHits)
stream.select("patMuon_patMuons.globalTrack_normalizedChi2", muon_globalTrack_normalizedChi2)
stream.select("patMuon_patMuons.innerTrack_dxy", muon_innerTrack_dxy)
stream.select("patMuon_patMuons.innerTrack_dz", muon_innerTrack_dz)
stream.select("patMuon_patMuons.innerTrack_hitPattern_numberOfValidPixelHits", muon_innerTrack_hitPattern_numberOfValidPixelHits)
stream.select("patMuon_patMuons.innerTrack_hitPattern_pixelLayersWithMeasurement", muon_innerTrack_hitPattern_pixelLayersWithMeasurement)
stream.select("patMuon_patMuons.innerTrack_normalizedChi2", muon_innerTrack_normalizedChi2)
stream.select("patMuon_patMuons.isGlobalMuon", muon_isGlobalMuon)
stream.select("patMuon_patMuons.isPFMuon", muon_isPFMuon)
stream.select("patMuon_patMuons.isTrackerMuon", muon_isTrackerMuon)
stream.select("patMuon_patMuons.muonBestTrack_dxy", muon_muonBestTrack_dxy)
stream.select("patMuon_patMuons.muonBestTrack_dz", muon_muonBestTrack_dz)
stream.select("patMuon_patMuons.numberOfMatchedStations", muon_numberOfMatchedStations)
stream.select("patMuon_patMuons.p", muon_p)
stream.select("patMuon_patMuons.pfIsolationR03_sumChargedHadronPt", muon_pfIsolationR03_sumChargedHadronPt)
stream.select("patMuon_patMuons.pfIsolationR03_sumChargedParticlePt", muon_pfIsolationR03_sumChargedParticlePt)
stream.select("patMuon_patMuons.pfIsolationR03_sumNeutralHadronEt", muon_pfIsolationR03_sumNeutralHadronEt)
stream.select("patMuon_patMuons.pfIsolationR03_sumNeutralHadronEtHighThreshold", muon_pfIsolationR03_sumNeutralHadronEtHighThreshold)
stream.select("patMuon_patMuons.pfIsolationR03_sumPUPt", muon_pfIsolationR03_sumPUPt)
stream.select("patMuon_patMuons.pfIsolationR03_sumPhotonEt", muon_pfIsolationR03_sumPhotonEt)
stream.select("patMuon_patMuons.pfIsolationR03_sumPhotonEtHighThreshold", muon_pfIsolationR03_sumPhotonEtHighThreshold)
stream.select("patMuon_patMuons.pfIsolationR04_sumChargedHadronPt", muon_pfIsolationR04_sumChargedHadronPt)
stream.select("patMuon_patMuons.pfIsolationR04_sumChargedParticlePt", muon_pfIsolationR04_sumChargedParticlePt)
stream.select("patMuon_patMuons.pfIsolationR04_sumNeutralHadronEt", muon_pfIsolationR04_sumNeutralHadronEt)
stream.select("patMuon_patMuons.pfIsolationR04_sumNeutralHadronEtHighThreshold", muon_pfIsolationR04_sumNeutralHadronEtHighThreshold)
stream.select("patMuon_patMuons.pfIsolationR04_sumPUPt", muon_pfIsolationR04_sumPUPt)
stream.select("patMuon_patMuons.pfIsolationR04_sumPhotonEt", muon_pfIsolationR04_sumPhotonEt)
stream.select("patMuon_patMuons.pfIsolationR04_sumPhotonEtHighThreshold", muon_pfIsolationR04_sumPhotonEtHighThreshold)
stream.select("patMuon_patMuons.phi", muon_phi)
stream.select("patMuon_patMuons.pt", muon_pt)
stream.select("patMuon_patMuons.px", muon_px)
stream.select("patMuon_patMuons.py", muon_py)
stream.select("patMuon_patMuons.pz", muon_pz)
stream.select("npatElectron_patElectrons", nelectron)
stream.select("nrecoGenParticleHelper_genParticles", ngenparticlehelper)
stream.select("nrecoGsfElectron_gsfElectrons", ngsfelectron)
stream.select("npatJet_selectedPatJets", njet)
stream.select("npatMET_patMETs", nmet)
stream.select("npatMuon_patMuons", nmuon)
stream.select("nrecoPFMET_pfType1CorrectedMet", npfmet)
stream.select("nrecoPFMET_pfType1p2CorrectedMet", npfmet2)
stream.select("nPileupSummaryInfo_addPileupInfo", npileupsummaryinfo)
stream.select("npatTauHelper_patTaus", ntauhelper)
stream.select("nrecoVertex_offlinePrimaryVertices", nvertex)
stream.select("recoPFMET_pfType1p2CorrectedMet.energy", pfmet2_energy)
stream.select("recoPFMET_pfType1p2CorrectedMet.et", pfmet2_et)
stream.select("recoPFMET_pfType1p2CorrectedMet.eta", pfmet2_eta)
stream.select("recoPFMET_pfType1p2CorrectedMet.p", pfmet2_p)
stream.select("recoPFMET_pfType1p2CorrectedMet.phi", pfmet2_phi)
stream.select("recoPFMET_pfType1p2CorrectedMet.pt", pfmet2_pt)
stream.select("recoPFMET_pfType1p2CorrectedMet.px", pfmet2_px)
stream.select("recoPFMET_pfType1p2CorrectedMet.py", pfmet2_py)
stream.select("recoPFMET_pfType1p2CorrectedMet.pz", pfmet2_pz)
stream.select("recoPFMET_pfType1CorrectedMet.energy", pfmet_energy)
stream.select("recoPFMET_pfType1CorrectedMet.et", pfmet_et)
stream.select("recoPFMET_pfType1CorrectedMet.eta", pfmet_eta)
stream.select("recoPFMET_pfType1CorrectedMet.p", pfmet_p)
stream.select("recoPFMET_pfType1CorrectedMet.phi", pfmet_phi)
stream.select("recoPFMET_pfType1CorrectedMet.pt", pfmet_pt)
stream.select("recoPFMET_pfType1CorrectedMet.px", pfmet_px)
stream.select("recoPFMET_pfType1CorrectedMet.py", pfmet_py)
stream.select("recoPFMET_pfType1CorrectedMet.pz", pfmet_pz)
stream.select("PileupSummaryInfo_addPileupInfo.getBunchCrossing", pileupsummaryinfo_getBunchCrossing)
stream.select("PileupSummaryInfo_addPileupInfo.getPU_NumInteractions", pileupsummaryinfo_getPU_NumInteractions)
stream.select("patTauHelper_patTaus.charge", tauhelper_charge)
stream.select("patTauHelper_patTaus.energy", tauhelper_energy)
stream.select("patTauHelper_patTaus.et", tauhelper_et)
stream.select("patTauHelper_patTaus.eta", tauhelper_eta)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_energy", tauhelper_leadPFChargedHadrCand_energy)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_et", tauhelper_leadPFChargedHadrCand_et)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_eta", tauhelper_leadPFChargedHadrCand_eta)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_mass", tauhelper_leadPFChargedHadrCand_mass)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_massSqr", tauhelper_leadPFChargedHadrCand_massSqr)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_mt", tauhelper_leadPFChargedHadrCand_mt)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_mtSqr", tauhelper_leadPFChargedHadrCand_mtSqr)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_p", tauhelper_leadPFChargedHadrCand_p)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_phi", tauhelper_leadPFChargedHadrCand_phi)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_pt", tauhelper_leadPFChargedHadrCand_pt)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_px", tauhelper_leadPFChargedHadrCand_px)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_py", tauhelper_leadPFChargedHadrCand_py)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_pz", tauhelper_leadPFChargedHadrCand_pz)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_rapidity", tauhelper_leadPFChargedHadrCand_rapidity)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_theta", tauhelper_leadPFChargedHadrCand_theta)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_y", tauhelper_leadPFChargedHadrCand_y)
stream.select("patTauHelper_patTaus.p", tauhelper_p)
stream.select("patTauHelper_patTaus.phi", tauhelper_phi)
stream.select("patTauHelper_patTaus.pt", tauhelper_pt)
stream.select("patTauHelper_patTaus.px", tauhelper_px)
stream.select("patTauHelper_patTaus.py", tauhelper_py)
stream.select("patTauHelper_patTaus.pz", tauhelper_pz)
stream.select("patTauHelper_patTaus.signalPFChargedHadrCands_size", tauhelper_signalPFChargedHadrCands_size)
stream.select("patTauHelper_patTaus.tauID_againstElectronDeadECAL", tauhelper_tauID_againstElectronDeadECAL)
stream.select("patTauHelper_patTaus.tauID_againstElectronLoose", tauhelper_tauID_againstElectronLoose)
stream.select("patTauHelper_patTaus.tauID_againstElectronLooseMVA2", tauhelper_tauID_againstElectronLooseMVA2)
stream.select("patTauHelper_patTaus.tauID_againstElectronLooseMVA3", tauhelper_tauID_againstElectronLooseMVA3)
stream.select("patTauHelper_patTaus.tauID_againstElectronMVA", tauhelper_tauID_againstElectronMVA)
stream.select("patTauHelper_patTaus.tauID_againstElectronMVA2category", tauhelper_tauID_againstElectronMVA2category)
stream.select("patTauHelper_patTaus.tauID_againstElectronMVA2raw", tauhelper_tauID_againstElectronMVA2raw)
stream.select("patTauHelper_patTaus.tauID_againstElectronMVA3category", tauhelper_tauID_againstElectronMVA3category)
stream.select("patTauHelper_patTaus.tauID_againstElectronMVA3raw", tauhelper_tauID_againstElectronMVA3raw)
stream.select("patTauHelper_patTaus.tauID_againstElectronMedium", tauhelper_tauID_againstElectronMedium)
stream.select("patTauHelper_patTaus.tauID_againstElectronMediumMVA2", tauhelper_tauID_againstElectronMediumMVA2)
stream.select("patTauHelper_patTaus.tauID_againstElectronMediumMVA3", tauhelper_tauID_againstElectronMediumMVA3)
stream.select("patTauHelper_patTaus.tauID_againstElectronTight", tauhelper_tauID_againstElectronTight)
stream.select("patTauHelper_patTaus.tauID_againstElectronTightMVA2", tauhelper_tauID_againstElectronTightMVA2)
stream.select("patTauHelper_patTaus.tauID_againstElectronTightMVA3", tauhelper_tauID_againstElectronTightMVA3)
stream.select("patTauHelper_patTaus.tauID_againstElectronVLooseMVA2", tauhelper_tauID_againstElectronVLooseMVA2)
stream.select("patTauHelper_patTaus.tauID_againstElectronVTightMVA3", tauhelper_tauID_againstElectronVTightMVA3)
stream.select("patTauHelper_patTaus.tauID_againstMuonLoose", tauhelper_tauID_againstMuonLoose)
stream.select("patTauHelper_patTaus.tauID_againstMuonLoose2", tauhelper_tauID_againstMuonLoose2)
stream.select("patTauHelper_patTaus.tauID_againstMuonMedium", tauhelper_tauID_againstMuonMedium)
stream.select("patTauHelper_patTaus.tauID_againstMuonMedium2", tauhelper_tauID_againstMuonMedium2)
stream.select("patTauHelper_patTaus.tauID_againstMuonTight", tauhelper_tauID_againstMuonTight)
stream.select("patTauHelper_patTaus.tauID_againstMuonTight2", tauhelper_tauID_againstMuonTight2)
stream.select("patTauHelper_patTaus.tauID_byCombinedIsolationDeltaBetaCorrRaw", tauhelper_tauID_byCombinedIsolationDeltaBetaCorrRaw)
stream.select("patTauHelper_patTaus.tauID_byCombinedIsolationDeltaBetaCorrRaw3Hits", tauhelper_tauID_byCombinedIsolationDeltaBetaCorrRaw3Hits)
stream.select("patTauHelper_patTaus.tauID_byIsolationMVA2raw", tauhelper_tauID_byIsolationMVA2raw)
stream.select("patTauHelper_patTaus.tauID_byIsolationMVAraw", tauhelper_tauID_byIsolationMVAraw)
stream.select("patTauHelper_patTaus.tauID_byLooseCombinedIsolationDeltaBetaCorr", tauhelper_tauID_byLooseCombinedIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byLooseCombinedIsolationDeltaBetaCorr3Hits", tauhelper_tauID_byLooseCombinedIsolationDeltaBetaCorr3Hits)
stream.select("patTauHelper_patTaus.tauID_byLooseIsolation", tauhelper_tauID_byLooseIsolation)
stream.select("patTauHelper_patTaus.tauID_byLooseIsolationDeltaBetaCorr", tauhelper_tauID_byLooseIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byLooseIsolationMVA", tauhelper_tauID_byLooseIsolationMVA)
stream.select("patTauHelper_patTaus.tauID_byLooseIsolationMVA2", tauhelper_tauID_byLooseIsolationMVA2)
stream.select("patTauHelper_patTaus.tauID_byMediumCombinedIsolationDeltaBetaCorr", tauhelper_tauID_byMediumCombinedIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byMediumCombinedIsolationDeltaBetaCorr3Hits", tauhelper_tauID_byMediumCombinedIsolationDeltaBetaCorr3Hits)
stream.select("patTauHelper_patTaus.tauID_byMediumIsolation", tauhelper_tauID_byMediumIsolation)
stream.select("patTauHelper_patTaus.tauID_byMediumIsolationDeltaBetaCorr", tauhelper_tauID_byMediumIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byMediumIsolationMVA", tauhelper_tauID_byMediumIsolationMVA)
stream.select("patTauHelper_patTaus.tauID_byMediumIsolationMVA2", tauhelper_tauID_byMediumIsolationMVA2)
stream.select("patTauHelper_patTaus.tauID_byTightCombinedIsolationDeltaBetaCorr", tauhelper_tauID_byTightCombinedIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byTightCombinedIsolationDeltaBetaCorr3Hits", tauhelper_tauID_byTightCombinedIsolationDeltaBetaCorr3Hits)
stream.select("patTauHelper_patTaus.tauID_byTightIsolation", tauhelper_tauID_byTightIsolation)
stream.select("patTauHelper_patTaus.tauID_byTightIsolationDeltaBetaCorr", tauhelper_tauID_byTightIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byTightIsolationMVA", tauhelper_tauID_byTightIsolationMVA)
stream.select("patTauHelper_patTaus.tauID_byTightIsolationMVA2", tauhelper_tauID_byTightIsolationMVA2)
stream.select("patTauHelper_patTaus.tauID_byVLooseCombinedIsolationDeltaBetaCorr", tauhelper_tauID_byVLooseCombinedIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byVLooseIsolation", tauhelper_tauID_byVLooseIsolation)
stream.select("patTauHelper_patTaus.tauID_byVLooseIsolationDeltaBetaCorr", tauhelper_tauID_byVLooseIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_decayModeFinding", tauhelper_tauID_decayModeFinding)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_DoubleMediumIsoPFTau35_Trk5_eta2p1_v6", triggerresultshelper_prescale_HLT_DoubleMediumIsoPFTau35_Trk5_eta2p1_v6)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.value_HLT_DoubleMediumIsoPFTau35_Trk5_eta2p1_v6", triggerresultshelper_value_HLT_DoubleMediumIsoPFTau35_Trk5_eta2p1_v6)
stream.select("recoVertex_offlinePrimaryVertices.isFake", vertex_isFake)
stream.select("recoVertex_offlinePrimaryVertices.ndof", vertex_ndof)
stream.select("recoVertex_offlinePrimaryVertices.x", vertex_x)
stream.select("recoVertex_offlinePrimaryVertices.y", vertex_y)
stream.select("recoVertex_offlinePrimaryVertices.z", vertex_z)

