# -----------------------------------------------------------------------------
#  File:        analyzerlib.py
#  Description: Analyzer for ntuples created by TheNtupleMaker
#  Created:     Wed Jul 15 15:50:51 2015 by mkanalyzer.py
#  Author:      Daniele Marconi
# -----------------------------------------------------------------------------
import os, sys, re
from ROOT import *
from string import atof, atoi, split, strip, replace
from array import array
from math import *
from time import sleep
from sys import exit
# -----------------------------------------------------------------------------
gSystem.AddIncludePath("-Iinclude")
gROOT.ProcessLine(".L src/treestream.cc+")
gROOT.ProcessLine(".L src/pdg.cc+")
# -----------------------------------------------------------------------------
# -- Classes, procedures and functions
# -----------------------------------------------------------------------------
class outputFile:

	def __init__(self, filename, stream=None, savecount=50000):
		if stream != None:
			print "events will be skimmed to file", filename			
			self.tree = stream.tree().CloneTree(0)
			self.weight = Double()
			self.b_weight = self.tree.Branch("eventWeight", self.weight,
											 "eventWeight/D")
			self.SAVECOUNT = savecount
		else:
			self.tree = None
			self.b_weight = None

		self.entry = 0

		self.filename = filename
		self.file = TFile(filename, "recreate")

		self.hist = TH1F("counts", "", 1, 0, 1)
		self.hist.SetBit(TH1.kCanRebin)
		self.hist.SetStats(0)

		self.b_weight = 0

	def addEvent(self, weight=1.0):
		if self.tree == None: return

		self.file = self.tree.GetCurrentFile()
		self.file.cd()
		self.tree.Fill()

		self.entry += 1		
		if self.entry % self.SAVECOUNT == 0:
			self.tree.AutoSave("SaveSelf")

	def count(self, cond, w=1.0):
		self.hist.Fill(cond, w)

	def close(self):
		print "==> histograms saved to file", self.filename
		if self.tree != None:			
			print "==> events skimmed to file", self.filename
			self.file = self.tree.GetCurrentFile()

		self.file.cd()
		#self.file.Write("", TObject.kOverwrite)
		self.file.Write()
		self.file.ls()
		self.file.Close()
# -----------------------------------------------------------------------------
class commandLine:
	def __init__(self):
		pass

def decodeCommandLine():
	argv = sys.argv
	argc = len(argv)

	cl = commandLine()
	cl.progname = split(os.path.basename(argv[0]),'.')[0]

	if argc > 1:
		cl.filelist = argv[1]
	else:
		cl.filelist = "filelist.txt"

	if argc > 2: 
		cl.outputfilename = argv[2] # 2nd (optional) command line argument
	else:
		cl.outputfilename = cl.progname + "_histograms"

	# Make sure extension is ".root"
	if cl.outputfilename[:-5] != ".root": cl.outputfilename += ".root"
	print "==> output to:", cl.outputfilename

	return cl
# -----------------------------------------------------------------------------
def error(message):
	print "** error ** " + message
	sys.exit(0)
# -----------------------------------------------------------------------------
#  Read ntuple filenames from file list

def getFilenames(filelist):
	if not os.path.exists(filelist):
		error("unable to open file: " + filelist)

	# Get ntuple file names
	filenames = filter(lambda x: x != "",
					   map(strip, open(filelist).readlines()))
	v = vector("string")()
	for filename in filenames: v.push_back(filename)
	return v
# -----------------------------------------------------------------------------
TEXTFONT = 42
TEXTSIZE = 0.031
#------------------------------------------------------------------------------
def setStyle():
	gROOT.SetStyle("Pub")
	style = gROOT.GetStyle("Pub")
	style.SetPalette(1)

	# For the canvas
	style.SetCanvasBorderMode(0)
	style.SetCanvasColor(kWhite)
	style.SetCanvasDefH(500)
	style.SetCanvasDefW(500)
	style.SetCanvasDefX(0)
	style.SetCanvasDefY(0)

	# For the pad
	style.SetPadBorderMode(0)
	style.SetPadColor(kWhite)
	style.SetPadGridX(kFALSE)
	style.SetPadGridY(kTRUE)
	style.SetGridColor(kGreen)
	style.SetGridStyle(3)
	style.SetGridWidth(1)

	# For the frame
	style.SetFrameBorderMode(0)
	style.SetFrameBorderSize(1)
	style.SetFrameFillColor(0)
	style.SetFrameFillStyle(0)
	style.SetFrameLineColor(1)
	style.SetFrameLineStyle(1)
	style.SetFrameLineWidth(1)

	# For the histogram
	style.SetHistLineColor(1)
	style.SetHistLineStyle(0)
	style.SetHistLineWidth(1)
	style.SetEndErrorSize(2)
	#style.SetErrorX(0.)
	style.SetMarkerSize(0.1)
	style.SetMarkerStyle(20)

	# For the fit/function
	style.SetOptFit(1)
	style.SetFitFormat("5.4g")
	style.SetFuncColor(2)
	style.SetFuncStyle(1)
	style.SetFuncWidth(1)

	#For the date
	style.SetOptDate(0)

	# For the statistics box
	style.SetOptFile(0)
	style.SetOptStat("")
	# To display the mean and RMS
	#style.SetOptStat("mr") 
	style.SetStatColor(kWhite)
	style.SetStatFont(TEXTFONT)
	style.SetStatFontSize(TEXTSIZE)
	style.SetStatTextColor(1)
	style.SetStatFormat("6.4g")
	style.SetStatBorderSize(1)
	style.SetStatH(0.2)
	style.SetStatW(0.3)

	# Margins
	style.SetPadTopMargin(0.05)
	style.SetPadBottomMargin(0.16)
	style.SetPadLeftMargin(0.16)
	style.SetPadRightMargin(0.16)

	# For the global title
	style.SetOptTitle(0)
	style.SetTitleFont(TEXTFONT)
	style.SetTitleColor(1)
	style.SetTitleTextColor(1)
	style.SetTitleFillColor(10)
	style.SetTitleFontSize(TEXTSIZE*1.1)

	# For the axis titles
	style.SetTitleColor(1, "XYZ")
	style.SetTitleFont(TEXTFONT, "XYZ")
	style.SetTitleSize(TEXTSIZE*1.2, "XYZ") # 0,05
	style.SetTitleXOffset(1.25) # 0.9
	style.SetTitleYOffset(1.25) # 1.25

	# For the axis labels
	style.SetLabelColor(1, "XYZ")
	style.SetLabelFont(TEXTFONT, "XYZ")
	style.SetLabelOffset(0.006, "XYZ")
	style.SetLabelSize(TEXTSIZE*1.2, "XYZ")

	# For the axis
	style.SetAxisColor(1, "XYZ")
	style.SetStripDecimals(kTRUE)
	style.SetTickLength(0.03, "XYZ")
	style.SetNdivisions(505, "XYZ")

	# To get tick marks on the opposite side of the frame
	style.SetPadTickX(1)  
	style.SetPadTickY(1)

	# Change for log plots
	style.SetOptLogx(0)
	style.SetOptLogy(0)
	style.SetOptLogz(0)

	# Postscript options
	style.SetPaperSize(20.,20.)

	style.cd()
# -----------------------------------------------------------------------------
#  Define variables to be read
# -----------------------------------------------------------------------------
beamppot_x0	= Double()
beamppot_y0	= Double()
beamppot_z0	= Double()
electron_caloIso	= vector("double")(7)
electron_charge	= vector("double")(7)
electron_deltaEtaSuperClusterTrackAtVtx	= vector("double")(7)
electron_deltaPhiSuperClusterTrackAtVtx	= vector("double")(7)
electron_dr04EcalRecHitSumEt	= vector("double")(7)
electron_dr04TkSumPt	= vector("double")(7)
electron_eSuperClusterOverP	= vector("double")(7)
electron_ecalIso	= vector("double")(7)
electron_energy	= vector("double")(7)
electron_et	= vector("double")(7)
electron_eta	= vector("double")(7)
electron_gsfTrack_d0	= vector("double")(7)
electron_gsfTrack_dxy	= vector("double")(7)
electron_gsfTrack_dz	= vector("double")(7)
electron_hadronicOverEm	= vector("double")(7)
electron_hcalIso	= vector("double")(7)
electron_isPF	= vector("double")(7)
electron_p	= vector("double")(7)
electron_phi	= vector("double")(7)
electron_pt	= vector("double")(7)
electron_px	= vector("double")(7)
electron_py	= vector("double")(7)
electron_pz	= vector("double")(7)
electron_scE1x5	= vector("double")(7)
electron_scE2x5Max	= vector("double")(7)
electron_scE5x5	= vector("double")(7)
electron_trackIso	= vector("double")(7)
genparticlehelper_charge	= vector("double")(39)
genparticlehelper_energy	= vector("double")(39)
genparticlehelper_eta	= vector("double")(39)
genparticlehelper_firstDaughter	= vector("double")(39)
genparticlehelper_firstMother	= vector("double")(39)
genparticlehelper_lastDaughter	= vector("double")(39)
genparticlehelper_lastMother	= vector("double")(39)
genparticlehelper_mass	= vector("double")(39)
genparticlehelper_pdgId	= vector("double")(39)
genparticlehelper_phi	= vector("double")(39)
genparticlehelper_pt	= vector("double")(39)
genparticlehelper_status	= vector("double")(39)
jet_HFEMEnergy	= vector("double")(31)
jet_HFEMEnergyFraction	= vector("double")(31)
jet_HFEMMultiplicity	= vector("double")(31)
jet_HFHadronEnergy	= vector("double")(31)
jet_HFHadronEnergyFraction	= vector("double")(31)
jet_HFHadronMultiplicity	= vector("double")(31)
jet_charge	= vector("double")(31)
jet_chargedEmEnergyFraction	= vector("double")(31)
jet_chargedHadronEnergyFraction	= vector("double")(31)
jet_chargedHadronMultiplicity	= vector("double")(31)
jet_chargedMuEnergy	= vector("double")(31)
jet_chargedMuEnergyFraction	= vector("double")(31)
jet_electronEnergy	= vector("double")(31)
jet_electronEnergyFraction	= vector("double")(31)
jet_electronMultiplicity	= vector("double")(31)
jet_energy	= vector("double")(31)
jet_et	= vector("double")(31)
jet_eta	= vector("double")(31)
jet_hadronFlavour	= vector("double")(31)
jet_muonEnergy	= vector("double")(31)
jet_muonEnergyFraction	= vector("double")(31)
jet_neutralEmEnergyFraction	= vector("double")(31)
jet_neutralHadronEnergy	= vector("double")(31)
jet_neutralHadronEnergyFraction	= vector("double")(31)
jet_neutralHadronMultiplicity	= vector("double")(31)
jet_neutralMultiplicity	= vector("double")(31)
jet_numberOfDaughters	= vector("double")(31)
jet_p	= vector("double")(31)
jet_partonFlavour	= vector("double")(31)
jet_phi	= vector("double")(31)
jet_photonEnergy	= vector("double")(31)
jet_photonEnergyFraction	= vector("double")(31)
jet_photonMultiplicity	= vector("double")(31)
jet_pt	= vector("double")(31)
jet_px	= vector("double")(31)
jet_py	= vector("double")(31)
jet_pz	= vector("double")(31)
met_energy	= vector("double")(3)
met_et	= vector("double")(3)
met_eta	= vector("double")(3)
met_p	= vector("double")(3)
met_phi	= vector("double")(3)
met_pt	= vector("double")(3)
met_px	= vector("double")(3)
met_py	= vector("double")(3)
met_pz	= vector("double")(3)
muon_charge	= vector("double")(11)
muon_energy	= vector("double")(11)
muon_et	= vector("double")(11)
muon_eta	= vector("double")(11)
muon_globalTrack_hitPattern_numberOfValidMuonHits	= vector("double")(11)
muon_globalTrack_normalizedChi2	= vector("double")(11)
muon_innerTrack_dxy	= vector("double")(11)
muon_innerTrack_dz	= vector("double")(11)
muon_innerTrack_hitPattern_numberOfValidPixelHits	= vector("double")(11)
muon_innerTrack_hitPattern_pixelLayersWithMeasurement	= vector("double")(11)
muon_innerTrack_normalizedChi2	= vector("double")(11)
muon_isGlobalMuon	= vector("double")(11)
muon_isPFMuon	= vector("double")(11)
muon_isTrackerMuon	= vector("double")(11)
muon_muonBestTrack_dxy	= vector("double")(11)
muon_muonBestTrack_dz	= vector("double")(11)
muon_numberOfMatchedStations	= vector("double")(11)
muon_p	= vector("double")(11)
muon_pfIsolationR03_sumChargedHadronPt	= vector("double")(11)
muon_pfIsolationR03_sumChargedParticlePt	= vector("double")(11)
muon_pfIsolationR03_sumNeutralHadronEt	= vector("double")(11)
muon_pfIsolationR03_sumNeutralHadronEtHighThreshold	= vector("double")(11)
muon_pfIsolationR03_sumPUPt	= vector("double")(11)
muon_pfIsolationR03_sumPhotonEt	= vector("double")(11)
muon_pfIsolationR03_sumPhotonEtHighThreshold	= vector("double")(11)
muon_pfIsolationR04_sumChargedHadronPt	= vector("double")(11)
muon_pfIsolationR04_sumChargedParticlePt	= vector("double")(11)
muon_pfIsolationR04_sumNeutralHadronEt	= vector("double")(11)
muon_pfIsolationR04_sumNeutralHadronEtHighThreshold	= vector("double")(11)
muon_pfIsolationR04_sumPUPt	= vector("double")(11)
muon_pfIsolationR04_sumPhotonEt	= vector("double")(11)
muon_pfIsolationR04_sumPhotonEtHighThreshold	= vector("double")(11)
muon_phi	= vector("double")(11)
muon_pt	= vector("double")(11)
muon_px	= vector("double")(11)
muon_py	= vector("double")(11)
muon_pz	= vector("double")(11)
nelectron	= Long()
ngenparticlehelper	= Long()
njet	= Long()
nmet	= Long()
nmuon	= Long()
ntau	= Long()
nvertex	= Long()
tau_charge	= vector("double")(7)
tau_energy	= vector("double")(7)
tau_et	= vector("double")(7)
tau_eta	= vector("double")(7)
tau_leadChargedHadrCand_energy	= vector("double")(7)
tau_leadChargedHadrCand_et	= vector("double")(7)
tau_leadChargedHadrCand_eta	= vector("double")(7)
tau_leadChargedHadrCand_mass	= vector("double")(7)
tau_leadChargedHadrCand_massSqr	= vector("double")(7)
tau_leadChargedHadrCand_mt	= vector("double")(7)
tau_leadChargedHadrCand_mtSqr	= vector("double")(7)
tau_leadChargedHadrCand_p	= vector("double")(7)
tau_leadChargedHadrCand_phi	= vector("double")(7)
tau_leadChargedHadrCand_pt	= vector("double")(7)
tau_leadChargedHadrCand_px	= vector("double")(7)
tau_leadChargedHadrCand_py	= vector("double")(7)
tau_leadChargedHadrCand_pz	= vector("double")(7)
tau_leadChargedHadrCand_rapidity	= vector("double")(7)
tau_leadChargedHadrCand_theta	= vector("double")(7)
tau_leadChargedHadrCand_y	= vector("double")(7)
tau_p	= vector("double")(7)
tau_phi	= vector("double")(7)
tau_pt	= vector("double")(7)
tau_px	= vector("double")(7)
tau_py	= vector("double")(7)
tau_pz	= vector("double")(7)
tau_tauID_againstElectronLoose	= vector("double")(7)
tau_tauID_againstElectronLooseMVA5	= vector("double")(7)
tau_tauID_againstElectronMVA5category	= vector("double")(7)
tau_tauID_againstElectronMVA5raw	= vector("double")(7)
tau_tauID_againstElectronMedium	= vector("double")(7)
tau_tauID_againstElectronMediumMVA5	= vector("double")(7)
tau_tauID_againstElectronTight	= vector("double")(7)
tau_tauID_againstElectronTightMVA5	= vector("double")(7)
tau_tauID_againstElectronVLooseMVA5	= vector("double")(7)
tau_tauID_againstElectronVTightMVA5	= vector("double")(7)
tau_tauID_againstMuonLoose	= vector("double")(7)
tau_tauID_againstMuonLoose2	= vector("double")(7)
tau_tauID_againstMuonLoose3	= vector("double")(7)
tau_tauID_againstMuonLooseMVA	= vector("double")(7)
tau_tauID_againstMuonMVAraw	= vector("double")(7)
tau_tauID_againstMuonMedium	= vector("double")(7)
tau_tauID_againstMuonMedium2	= vector("double")(7)
tau_tauID_againstMuonMediumMVA	= vector("double")(7)
tau_tauID_againstMuonTight	= vector("double")(7)
tau_tauID_againstMuonTight2	= vector("double")(7)
tau_tauID_againstMuonTight3	= vector("double")(7)
tau_tauID_againstMuonTightMVA	= vector("double")(7)
tau_tauID_byCombinedIsolationDeltaBetaCorrRaw3Hits	= vector("double")(7)
tau_tauID_byIsolationMVA3newDMwLTraw	= vector("double")(7)
tau_tauID_byIsolationMVA3newDMwoLTraw	= vector("double")(7)
tau_tauID_byIsolationMVA3oldDMwLTraw	= vector("double")(7)
tau_tauID_byIsolationMVA3oldDMwoLTraw	= vector("double")(7)
tau_tauID_byLooseCombinedIsolationDeltaBetaCorr3Hits	= vector("double")(7)
tau_tauID_byLooseIsolationMVA3newDMwLT	= vector("double")(7)
tau_tauID_byLooseIsolationMVA3newDMwoLT	= vector("double")(7)
tau_tauID_byLooseIsolationMVA3oldDMwLT	= vector("double")(7)
tau_tauID_byLooseIsolationMVA3oldDMwoLT	= vector("double")(7)
tau_tauID_byMediumCombinedIsolationDeltaBetaCorr3Hits	= vector("double")(7)
tau_tauID_byMediumIsolationMVA3newDMwLT	= vector("double")(7)
tau_tauID_byMediumIsolationMVA3newDMwoLT	= vector("double")(7)
tau_tauID_byMediumIsolationMVA3oldDMwLT	= vector("double")(7)
tau_tauID_byMediumIsolationMVA3oldDMwoLT	= vector("double")(7)
tau_tauID_byTightCombinedIsolationDeltaBetaCorr3Hits	= vector("double")(7)
tau_tauID_byTightIsolationMVA3newDMwLT	= vector("double")(7)
tau_tauID_byTightIsolationMVA3newDMwoLT	= vector("double")(7)
tau_tauID_byTightIsolationMVA3oldDMwLT	= vector("double")(7)
tau_tauID_byTightIsolationMVA3oldDMwoLT	= vector("double")(7)
tau_tauID_byVLooseIsolationMVA3newDMwLT	= vector("double")(7)
tau_tauID_byVLooseIsolationMVA3newDMwoLT	= vector("double")(7)
tau_tauID_byVLooseIsolationMVA3oldDMwLT	= vector("double")(7)
tau_tauID_byVLooseIsolationMVA3oldDMwoLT	= vector("double")(7)
tau_tauID_byVTightIsolationMVA3newDMwLT	= vector("double")(7)
tau_tauID_byVTightIsolationMVA3newDMwoLT	= vector("double")(7)
tau_tauID_byVTightIsolationMVA3oldDMwLT	= vector("double")(7)
tau_tauID_byVTightIsolationMVA3oldDMwoLT	= vector("double")(7)
tau_tauID_byVVTightIsolationMVA3newDMwLT	= vector("double")(7)
tau_tauID_byVVTightIsolationMVA3newDMwoLT	= vector("double")(7)
tau_tauID_byVVTightIsolationMVA3oldDMwLT	= vector("double")(7)
tau_tauID_byVVTightIsolationMVA3oldDMwoLT	= vector("double")(7)
tau_tauID_chargedIsoPtSum	= vector("double")(7)
tau_tauID_decayModeFinding	= vector("double")(7)
tau_tauID_decayModeFindingNewDMs	= vector("double")(7)
tau_tauID_neutralIsoPtSum	= vector("double")(7)
tau_tauID_puCorrPtSum	= vector("double")(7)
vertex_chi2	= vector("double")(35)
vertex_isFake	= vector("double")(35)
vertex_isValid	= vector("double")(35)
vertex_ndof	= vector("double")(35)
vertex_x	= vector("double")(35)
vertex_y	= vector("double")(35)
vertex_z	= vector("double")(35)

stream.select("recoBeamSpot_offlineBeamSpot.x0", beamppot_x0)
stream.select("recoBeamSpot_offlineBeamSpot.y0", beamppot_y0)
stream.select("recoBeamSpot_offlineBeamSpot.z0", beamppot_z0)
stream.select("patElectron_slimmedElectrons.caloIso", electron_caloIso)
stream.select("patElectron_slimmedElectrons.charge", electron_charge)
stream.select("patElectron_slimmedElectrons.deltaEtaSuperClusterTrackAtVtx", electron_deltaEtaSuperClusterTrackAtVtx)
stream.select("patElectron_slimmedElectrons.deltaPhiSuperClusterTrackAtVtx", electron_deltaPhiSuperClusterTrackAtVtx)
stream.select("patElectron_slimmedElectrons.dr04EcalRecHitSumEt", electron_dr04EcalRecHitSumEt)
stream.select("patElectron_slimmedElectrons.dr04TkSumPt", electron_dr04TkSumPt)
stream.select("patElectron_slimmedElectrons.eSuperClusterOverP", electron_eSuperClusterOverP)
stream.select("patElectron_slimmedElectrons.ecalIso", electron_ecalIso)
stream.select("patElectron_slimmedElectrons.energy", electron_energy)
stream.select("patElectron_slimmedElectrons.et", electron_et)
stream.select("patElectron_slimmedElectrons.eta", electron_eta)
stream.select("patElectron_slimmedElectrons.gsfTrack_d0", electron_gsfTrack_d0)
stream.select("patElectron_slimmedElectrons.gsfTrack_dxy", electron_gsfTrack_dxy)
stream.select("patElectron_slimmedElectrons.gsfTrack_dz", electron_gsfTrack_dz)
stream.select("patElectron_slimmedElectrons.hadronicOverEm", electron_hadronicOverEm)
stream.select("patElectron_slimmedElectrons.hcalIso", electron_hcalIso)
stream.select("patElectron_slimmedElectrons.isPF", electron_isPF)
stream.select("patElectron_slimmedElectrons.p", electron_p)
stream.select("patElectron_slimmedElectrons.phi", electron_phi)
stream.select("patElectron_slimmedElectrons.pt", electron_pt)
stream.select("patElectron_slimmedElectrons.px", electron_px)
stream.select("patElectron_slimmedElectrons.py", electron_py)
stream.select("patElectron_slimmedElectrons.pz", electron_pz)
stream.select("patElectron_slimmedElectrons.scE1x5", electron_scE1x5)
stream.select("patElectron_slimmedElectrons.scE2x5Max", electron_scE2x5Max)
stream.select("patElectron_slimmedElectrons.scE5x5", electron_scE5x5)
stream.select("patElectron_slimmedElectrons.trackIso", electron_trackIso)
stream.select("recoGenParticleHelper2_prunedGenParticles.charge", genparticlehelper_charge)
stream.select("recoGenParticleHelper2_prunedGenParticles.energy", genparticlehelper_energy)
stream.select("recoGenParticleHelper2_prunedGenParticles.eta", genparticlehelper_eta)
stream.select("recoGenParticleHelper2_prunedGenParticles.firstDaughter", genparticlehelper_firstDaughter)
stream.select("recoGenParticleHelper2_prunedGenParticles.firstMother", genparticlehelper_firstMother)
stream.select("recoGenParticleHelper2_prunedGenParticles.lastDaughter", genparticlehelper_lastDaughter)
stream.select("recoGenParticleHelper2_prunedGenParticles.lastMother", genparticlehelper_lastMother)
stream.select("recoGenParticleHelper2_prunedGenParticles.mass", genparticlehelper_mass)
stream.select("recoGenParticleHelper2_prunedGenParticles.pdgId", genparticlehelper_pdgId)
stream.select("recoGenParticleHelper2_prunedGenParticles.phi", genparticlehelper_phi)
stream.select("recoGenParticleHelper2_prunedGenParticles.pt", genparticlehelper_pt)
stream.select("recoGenParticleHelper2_prunedGenParticles.status", genparticlehelper_status)
stream.select("patJet_slimmedJets.HFEMEnergy", jet_HFEMEnergy)
stream.select("patJet_slimmedJets.HFEMEnergyFraction", jet_HFEMEnergyFraction)
stream.select("patJet_slimmedJets.HFEMMultiplicity", jet_HFEMMultiplicity)
stream.select("patJet_slimmedJets.HFHadronEnergy", jet_HFHadronEnergy)
stream.select("patJet_slimmedJets.HFHadronEnergyFraction", jet_HFHadronEnergyFraction)
stream.select("patJet_slimmedJets.HFHadronMultiplicity", jet_HFHadronMultiplicity)
stream.select("patJet_slimmedJets.charge", jet_charge)
stream.select("patJet_slimmedJets.chargedEmEnergyFraction", jet_chargedEmEnergyFraction)
stream.select("patJet_slimmedJets.chargedHadronEnergyFraction", jet_chargedHadronEnergyFraction)
stream.select("patJet_slimmedJets.chargedHadronMultiplicity", jet_chargedHadronMultiplicity)
stream.select("patJet_slimmedJets.chargedMuEnergy", jet_chargedMuEnergy)
stream.select("patJet_slimmedJets.chargedMuEnergyFraction", jet_chargedMuEnergyFraction)
stream.select("patJet_slimmedJets.electronEnergy", jet_electronEnergy)
stream.select("patJet_slimmedJets.electronEnergyFraction", jet_electronEnergyFraction)
stream.select("patJet_slimmedJets.electronMultiplicity", jet_electronMultiplicity)
stream.select("patJet_slimmedJets.energy", jet_energy)
stream.select("patJet_slimmedJets.et", jet_et)
stream.select("patJet_slimmedJets.eta", jet_eta)
stream.select("patJet_slimmedJets.hadronFlavour", jet_hadronFlavour)
stream.select("patJet_slimmedJets.muonEnergy", jet_muonEnergy)
stream.select("patJet_slimmedJets.muonEnergyFraction", jet_muonEnergyFraction)
stream.select("patJet_slimmedJets.neutralEmEnergyFraction", jet_neutralEmEnergyFraction)
stream.select("patJet_slimmedJets.neutralHadronEnergy", jet_neutralHadronEnergy)
stream.select("patJet_slimmedJets.neutralHadronEnergyFraction", jet_neutralHadronEnergyFraction)
stream.select("patJet_slimmedJets.neutralHadronMultiplicity", jet_neutralHadronMultiplicity)
stream.select("patJet_slimmedJets.neutralMultiplicity", jet_neutralMultiplicity)
stream.select("patJet_slimmedJets.numberOfDaughters", jet_numberOfDaughters)
stream.select("patJet_slimmedJets.p", jet_p)
stream.select("patJet_slimmedJets.partonFlavour", jet_partonFlavour)
stream.select("patJet_slimmedJets.phi", jet_phi)
stream.select("patJet_slimmedJets.photonEnergy", jet_photonEnergy)
stream.select("patJet_slimmedJets.photonEnergyFraction", jet_photonEnergyFraction)
stream.select("patJet_slimmedJets.photonMultiplicity", jet_photonMultiplicity)
stream.select("patJet_slimmedJets.pt", jet_pt)
stream.select("patJet_slimmedJets.px", jet_px)
stream.select("patJet_slimmedJets.py", jet_py)
stream.select("patJet_slimmedJets.pz", jet_pz)
stream.select("patMET_slimmedMETs.energy", met_energy)
stream.select("patMET_slimmedMETs.et", met_et)
stream.select("patMET_slimmedMETs.eta", met_eta)
stream.select("patMET_slimmedMETs.p", met_p)
stream.select("patMET_slimmedMETs.phi", met_phi)
stream.select("patMET_slimmedMETs.pt", met_pt)
stream.select("patMET_slimmedMETs.px", met_px)
stream.select("patMET_slimmedMETs.py", met_py)
stream.select("patMET_slimmedMETs.pz", met_pz)
stream.select("patMuon_slimmedMuons.charge", muon_charge)
stream.select("patMuon_slimmedMuons.energy", muon_energy)
stream.select("patMuon_slimmedMuons.et", muon_et)
stream.select("patMuon_slimmedMuons.eta", muon_eta)
stream.select("patMuon_slimmedMuons.globalTrack_hitPattern_numberOfValidMuonHits", muon_globalTrack_hitPattern_numberOfValidMuonHits)
stream.select("patMuon_slimmedMuons.globalTrack_normalizedChi2", muon_globalTrack_normalizedChi2)
stream.select("patMuon_slimmedMuons.innerTrack_dxy", muon_innerTrack_dxy)
stream.select("patMuon_slimmedMuons.innerTrack_dz", muon_innerTrack_dz)
stream.select("patMuon_slimmedMuons.innerTrack_hitPattern_numberOfValidPixelHits", muon_innerTrack_hitPattern_numberOfValidPixelHits)
stream.select("patMuon_slimmedMuons.innerTrack_hitPattern_pixelLayersWithMeasurement", muon_innerTrack_hitPattern_pixelLayersWithMeasurement)
stream.select("patMuon_slimmedMuons.innerTrack_normalizedChi2", muon_innerTrack_normalizedChi2)
stream.select("patMuon_slimmedMuons.isGlobalMuon", muon_isGlobalMuon)
stream.select("patMuon_slimmedMuons.isPFMuon", muon_isPFMuon)
stream.select("patMuon_slimmedMuons.isTrackerMuon", muon_isTrackerMuon)
stream.select("patMuon_slimmedMuons.muonBestTrack_dxy", muon_muonBestTrack_dxy)
stream.select("patMuon_slimmedMuons.muonBestTrack_dz", muon_muonBestTrack_dz)
stream.select("patMuon_slimmedMuons.numberOfMatchedStations", muon_numberOfMatchedStations)
stream.select("patMuon_slimmedMuons.p", muon_p)
stream.select("patMuon_slimmedMuons.pfIsolationR03_sumChargedHadronPt", muon_pfIsolationR03_sumChargedHadronPt)
stream.select("patMuon_slimmedMuons.pfIsolationR03_sumChargedParticlePt", muon_pfIsolationR03_sumChargedParticlePt)
stream.select("patMuon_slimmedMuons.pfIsolationR03_sumNeutralHadronEt", muon_pfIsolationR03_sumNeutralHadronEt)
stream.select("patMuon_slimmedMuons.pfIsolationR03_sumNeutralHadronEtHighThreshold", muon_pfIsolationR03_sumNeutralHadronEtHighThreshold)
stream.select("patMuon_slimmedMuons.pfIsolationR03_sumPUPt", muon_pfIsolationR03_sumPUPt)
stream.select("patMuon_slimmedMuons.pfIsolationR03_sumPhotonEt", muon_pfIsolationR03_sumPhotonEt)
stream.select("patMuon_slimmedMuons.pfIsolationR03_sumPhotonEtHighThreshold", muon_pfIsolationR03_sumPhotonEtHighThreshold)
stream.select("patMuon_slimmedMuons.pfIsolationR04_sumChargedHadronPt", muon_pfIsolationR04_sumChargedHadronPt)
stream.select("patMuon_slimmedMuons.pfIsolationR04_sumChargedParticlePt", muon_pfIsolationR04_sumChargedParticlePt)
stream.select("patMuon_slimmedMuons.pfIsolationR04_sumNeutralHadronEt", muon_pfIsolationR04_sumNeutralHadronEt)
stream.select("patMuon_slimmedMuons.pfIsolationR04_sumNeutralHadronEtHighThreshold", muon_pfIsolationR04_sumNeutralHadronEtHighThreshold)
stream.select("patMuon_slimmedMuons.pfIsolationR04_sumPUPt", muon_pfIsolationR04_sumPUPt)
stream.select("patMuon_slimmedMuons.pfIsolationR04_sumPhotonEt", muon_pfIsolationR04_sumPhotonEt)
stream.select("patMuon_slimmedMuons.pfIsolationR04_sumPhotonEtHighThreshold", muon_pfIsolationR04_sumPhotonEtHighThreshold)
stream.select("patMuon_slimmedMuons.phi", muon_phi)
stream.select("patMuon_slimmedMuons.pt", muon_pt)
stream.select("patMuon_slimmedMuons.px", muon_px)
stream.select("patMuon_slimmedMuons.py", muon_py)
stream.select("patMuon_slimmedMuons.pz", muon_pz)
stream.select("npatElectron_slimmedElectrons", nelectron)
stream.select("nrecoGenParticleHelper2_prunedGenParticles", ngenparticlehelper)
stream.select("npatJet_slimmedJets", njet)
stream.select("npatMET_slimmedMETs", nmet)
stream.select("npatMuon_slimmedMuons", nmuon)
stream.select("npatTau_slimmedTaus", ntau)
stream.select("nrecoVertex_offlineSlimmedPrimaryVertices", nvertex)
stream.select("patTau_slimmedTaus.charge", tau_charge)
stream.select("patTau_slimmedTaus.energy", tau_energy)
stream.select("patTau_slimmedTaus.et", tau_et)
stream.select("patTau_slimmedTaus.eta", tau_eta)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_energy", tau_leadChargedHadrCand_energy)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_et", tau_leadChargedHadrCand_et)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_eta", tau_leadChargedHadrCand_eta)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_mass", tau_leadChargedHadrCand_mass)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_massSqr", tau_leadChargedHadrCand_massSqr)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_mt", tau_leadChargedHadrCand_mt)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_mtSqr", tau_leadChargedHadrCand_mtSqr)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_p", tau_leadChargedHadrCand_p)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_phi", tau_leadChargedHadrCand_phi)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_pt", tau_leadChargedHadrCand_pt)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_px", tau_leadChargedHadrCand_px)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_py", tau_leadChargedHadrCand_py)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_pz", tau_leadChargedHadrCand_pz)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_rapidity", tau_leadChargedHadrCand_rapidity)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_theta", tau_leadChargedHadrCand_theta)
stream.select("patTau_slimmedTaus.leadChargedHadrCand_y", tau_leadChargedHadrCand_y)
stream.select("patTau_slimmedTaus.p", tau_p)
stream.select("patTau_slimmedTaus.phi", tau_phi)
stream.select("patTau_slimmedTaus.pt", tau_pt)
stream.select("patTau_slimmedTaus.px", tau_px)
stream.select("patTau_slimmedTaus.py", tau_py)
stream.select("patTau_slimmedTaus.pz", tau_pz)
stream.select("patTau_slimmedTaus.tauID_againstElectronLoose", tau_tauID_againstElectronLoose)
stream.select("patTau_slimmedTaus.tauID_againstElectronLooseMVA5", tau_tauID_againstElectronLooseMVA5)
stream.select("patTau_slimmedTaus.tauID_againstElectronMVA5category", tau_tauID_againstElectronMVA5category)
stream.select("patTau_slimmedTaus.tauID_againstElectronMVA5raw", tau_tauID_againstElectronMVA5raw)
stream.select("patTau_slimmedTaus.tauID_againstElectronMedium", tau_tauID_againstElectronMedium)
stream.select("patTau_slimmedTaus.tauID_againstElectronMediumMVA5", tau_tauID_againstElectronMediumMVA5)
stream.select("patTau_slimmedTaus.tauID_againstElectronTight", tau_tauID_againstElectronTight)
stream.select("patTau_slimmedTaus.tauID_againstElectronTightMVA5", tau_tauID_againstElectronTightMVA5)
stream.select("patTau_slimmedTaus.tauID_againstElectronVLooseMVA5", tau_tauID_againstElectronVLooseMVA5)
stream.select("patTau_slimmedTaus.tauID_againstElectronVTightMVA5", tau_tauID_againstElectronVTightMVA5)
stream.select("patTau_slimmedTaus.tauID_againstMuonLoose", tau_tauID_againstMuonLoose)
stream.select("patTau_slimmedTaus.tauID_againstMuonLoose2", tau_tauID_againstMuonLoose2)
stream.select("patTau_slimmedTaus.tauID_againstMuonLoose3", tau_tauID_againstMuonLoose3)
stream.select("patTau_slimmedTaus.tauID_againstMuonLooseMVA", tau_tauID_againstMuonLooseMVA)
stream.select("patTau_slimmedTaus.tauID_againstMuonMVAraw", tau_tauID_againstMuonMVAraw)
stream.select("patTau_slimmedTaus.tauID_againstMuonMedium", tau_tauID_againstMuonMedium)
stream.select("patTau_slimmedTaus.tauID_againstMuonMedium2", tau_tauID_againstMuonMedium2)
stream.select("patTau_slimmedTaus.tauID_againstMuonMediumMVA", tau_tauID_againstMuonMediumMVA)
stream.select("patTau_slimmedTaus.tauID_againstMuonTight", tau_tauID_againstMuonTight)
stream.select("patTau_slimmedTaus.tauID_againstMuonTight2", tau_tauID_againstMuonTight2)
stream.select("patTau_slimmedTaus.tauID_againstMuonTight3", tau_tauID_againstMuonTight3)
stream.select("patTau_slimmedTaus.tauID_againstMuonTightMVA", tau_tauID_againstMuonTightMVA)
stream.select("patTau_slimmedTaus.tauID_byCombinedIsolationDeltaBetaCorrRaw3Hits", tau_tauID_byCombinedIsolationDeltaBetaCorrRaw3Hits)
stream.select("patTau_slimmedTaus.tauID_byIsolationMVA3newDMwLTraw", tau_tauID_byIsolationMVA3newDMwLTraw)
stream.select("patTau_slimmedTaus.tauID_byIsolationMVA3newDMwoLTraw", tau_tauID_byIsolationMVA3newDMwoLTraw)
stream.select("patTau_slimmedTaus.tauID_byIsolationMVA3oldDMwLTraw", tau_tauID_byIsolationMVA3oldDMwLTraw)
stream.select("patTau_slimmedTaus.tauID_byIsolationMVA3oldDMwoLTraw", tau_tauID_byIsolationMVA3oldDMwoLTraw)
stream.select("patTau_slimmedTaus.tauID_byLooseCombinedIsolationDeltaBetaCorr3Hits", tau_tauID_byLooseCombinedIsolationDeltaBetaCorr3Hits)
stream.select("patTau_slimmedTaus.tauID_byLooseIsolationMVA3newDMwLT", tau_tauID_byLooseIsolationMVA3newDMwLT)
stream.select("patTau_slimmedTaus.tauID_byLooseIsolationMVA3newDMwoLT", tau_tauID_byLooseIsolationMVA3newDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byLooseIsolationMVA3oldDMwLT", tau_tauID_byLooseIsolationMVA3oldDMwLT)
stream.select("patTau_slimmedTaus.tauID_byLooseIsolationMVA3oldDMwoLT", tau_tauID_byLooseIsolationMVA3oldDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byMediumCombinedIsolationDeltaBetaCorr3Hits", tau_tauID_byMediumCombinedIsolationDeltaBetaCorr3Hits)
stream.select("patTau_slimmedTaus.tauID_byMediumIsolationMVA3newDMwLT", tau_tauID_byMediumIsolationMVA3newDMwLT)
stream.select("patTau_slimmedTaus.tauID_byMediumIsolationMVA3newDMwoLT", tau_tauID_byMediumIsolationMVA3newDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byMediumIsolationMVA3oldDMwLT", tau_tauID_byMediumIsolationMVA3oldDMwLT)
stream.select("patTau_slimmedTaus.tauID_byMediumIsolationMVA3oldDMwoLT", tau_tauID_byMediumIsolationMVA3oldDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byTightCombinedIsolationDeltaBetaCorr3Hits", tau_tauID_byTightCombinedIsolationDeltaBetaCorr3Hits)
stream.select("patTau_slimmedTaus.tauID_byTightIsolationMVA3newDMwLT", tau_tauID_byTightIsolationMVA3newDMwLT)
stream.select("patTau_slimmedTaus.tauID_byTightIsolationMVA3newDMwoLT", tau_tauID_byTightIsolationMVA3newDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byTightIsolationMVA3oldDMwLT", tau_tauID_byTightIsolationMVA3oldDMwLT)
stream.select("patTau_slimmedTaus.tauID_byTightIsolationMVA3oldDMwoLT", tau_tauID_byTightIsolationMVA3oldDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byVLooseIsolationMVA3newDMwLT", tau_tauID_byVLooseIsolationMVA3newDMwLT)
stream.select("patTau_slimmedTaus.tauID_byVLooseIsolationMVA3newDMwoLT", tau_tauID_byVLooseIsolationMVA3newDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byVLooseIsolationMVA3oldDMwLT", tau_tauID_byVLooseIsolationMVA3oldDMwLT)
stream.select("patTau_slimmedTaus.tauID_byVLooseIsolationMVA3oldDMwoLT", tau_tauID_byVLooseIsolationMVA3oldDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byVTightIsolationMVA3newDMwLT", tau_tauID_byVTightIsolationMVA3newDMwLT)
stream.select("patTau_slimmedTaus.tauID_byVTightIsolationMVA3newDMwoLT", tau_tauID_byVTightIsolationMVA3newDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byVTightIsolationMVA3oldDMwLT", tau_tauID_byVTightIsolationMVA3oldDMwLT)
stream.select("patTau_slimmedTaus.tauID_byVTightIsolationMVA3oldDMwoLT", tau_tauID_byVTightIsolationMVA3oldDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byVVTightIsolationMVA3newDMwLT", tau_tauID_byVVTightIsolationMVA3newDMwLT)
stream.select("patTau_slimmedTaus.tauID_byVVTightIsolationMVA3newDMwoLT", tau_tauID_byVVTightIsolationMVA3newDMwoLT)
stream.select("patTau_slimmedTaus.tauID_byVVTightIsolationMVA3oldDMwLT", tau_tauID_byVVTightIsolationMVA3oldDMwLT)
stream.select("patTau_slimmedTaus.tauID_byVVTightIsolationMVA3oldDMwoLT", tau_tauID_byVVTightIsolationMVA3oldDMwoLT)
stream.select("patTau_slimmedTaus.tauID_chargedIsoPtSum", tau_tauID_chargedIsoPtSum)
stream.select("patTau_slimmedTaus.tauID_decayModeFinding", tau_tauID_decayModeFinding)
stream.select("patTau_slimmedTaus.tauID_decayModeFindingNewDMs", tau_tauID_decayModeFindingNewDMs)
stream.select("patTau_slimmedTaus.tauID_neutralIsoPtSum", tau_tauID_neutralIsoPtSum)
stream.select("patTau_slimmedTaus.tauID_puCorrPtSum", tau_tauID_puCorrPtSum)
stream.select("recoVertex_offlineSlimmedPrimaryVertices.chi2", vertex_chi2)
stream.select("recoVertex_offlineSlimmedPrimaryVertices.isFake", vertex_isFake)
stream.select("recoVertex_offlineSlimmedPrimaryVertices.isValid", vertex_isValid)
stream.select("recoVertex_offlineSlimmedPrimaryVertices.ndof", vertex_ndof)
stream.select("recoVertex_offlineSlimmedPrimaryVertices.x", vertex_x)
stream.select("recoVertex_offlineSlimmedPrimaryVertices.y", vertex_y)
stream.select("recoVertex_offlineSlimmedPrimaryVertices.z", vertex_z)

