# -----------------------------------------------------------------------------
#  File:        analyzerlib.py
#  Description: Analyzer for ntuples created by TheNtupleMaker
#  Created:     Fri Jun 13 07:34:29 2014 by mkanalyzer.py
#  Author:      Shakepeare's ghost
# -----------------------------------------------------------------------------
import os, sys, re
from ROOT import *
from string import atof, atoi, split, strip, replace
from array import array
from math import *
from time import sleep
from sys import exit
# -----------------------------------------------------------------------------
gSystem.AddIncludePath("-Iinclude")
gROOT.ProcessLine(".L src/treestream.cc+")
gROOT.ProcessLine(".L src/pdg.cc+")
# -----------------------------------------------------------------------------
# -- Classes, procedures and functions
# -----------------------------------------------------------------------------
class outputFile:

	def __init__(self, filename, stream=None, savecount=50000):
		if stream != None:
			print "events will be skimmed to file", filename			
			self.tree = stream.tree().CloneTree(0)
			self.weight = Double()
			self.b_weight = self.tree.Branch("eventWeight", self.weight,
											 "eventWeight/D")
			self.SAVECOUNT = savecount
		else:
			self.tree = None
			self.b_weight = None

		self.entry = 0

		self.filename = filename
		self.file = TFile(filename, "recreate")

		self.hist = TH1F("counts", "", 1, 0, 1)
		self.hist.SetBit(TH1.kCanRebin)
		self.hist.SetStats(0)

		self.b_weight = 0

	def addEvent(self, weight=1.0):
		if self.tree == None: return

		self.file = self.tree.GetCurrentFile()
		self.file.cd()
		self.tree.Fill()

		self.entry += 1		
		if self.entry % self.SAVECOUNT == 0:
			self.tree.AutoSave("SaveSelf")

	def count(self, cond, w=1.0):
		self.hist.Fill(cond, w)

	def close(self):
		print "==> histograms saved to file", self.filename
		if self.tree != None:			
			print "==> events skimmed to file", self.filename
			self.file = self.tree.GetCurrentFile()

		self.file.cd()
		#self.file.Write("", TObject.kOverwrite)
		self.file.Write()
		self.file.ls()
		self.file.Close()
# -----------------------------------------------------------------------------
class commandLine:
	def __init__(self):
		pass

def decodeCommandLine():
	argv = sys.argv
	argc = len(argv)

	cl = commandLine()
	cl.progname = split(os.path.basename(argv[0]),'.')[0]

	if argc > 1:
		cl.filelist = argv[1]
	else:
		cl.filelist = "filelist.txt"

	if argc > 2: 
		cl.outputfilename = argv[2] # 2nd (optional) command line argument
	else:
		cl.outputfilename = cl.progname + "_histograms"

	# Make sure extension is ".root"
	if cl.outputfilename[:-5] != ".root": cl.outputfilename += ".root"
	print "==> output to:", cl.outputfilename

	return cl
# -----------------------------------------------------------------------------
def error(message):
	print "** error ** " + message
	sys.exit(0)
# -----------------------------------------------------------------------------
#  Read ntuple filenames from file list

def getFilenames(filelist):
	if not os.path.exists(filelist):
		error("unable to open file: " + filelist)

	# Get ntuple file names
	filenames = filter(lambda x: x != "",
					   map(strip, open(filelist).readlines()))
	v = vector("string")()
	for filename in filenames: v.push_back(filename)
	return v
# -----------------------------------------------------------------------------
TEXTFONT = 42
TEXTSIZE = 0.031
#------------------------------------------------------------------------------
def setStyle():
	gROOT.SetStyle("Pub")
	style = gROOT.GetStyle("Pub")
	style.SetPalette(1)

	# For the canvas
	style.SetCanvasBorderMode(0)
	style.SetCanvasColor(kWhite)
	style.SetCanvasDefH(500)
	style.SetCanvasDefW(500)
	style.SetCanvasDefX(0)
	style.SetCanvasDefY(0)

	# For the pad
	style.SetPadBorderMode(0)
	style.SetPadColor(kWhite)
	style.SetPadGridX(kFALSE)
	style.SetPadGridY(kTRUE)
	style.SetGridColor(kGreen)
	style.SetGridStyle(3)
	style.SetGridWidth(1)

	# For the frame
	style.SetFrameBorderMode(0)
	style.SetFrameBorderSize(1)
	style.SetFrameFillColor(0)
	style.SetFrameFillStyle(0)
	style.SetFrameLineColor(1)
	style.SetFrameLineStyle(1)
	style.SetFrameLineWidth(1)

	# For the histogram
	style.SetHistLineColor(1)
	style.SetHistLineStyle(0)
	style.SetHistLineWidth(1)
	style.SetEndErrorSize(2)
	#style.SetErrorX(0.)
	style.SetMarkerSize(0.1)
	style.SetMarkerStyle(20)

	# For the fit/function
	style.SetOptFit(1)
	style.SetFitFormat("5.4g")
	style.SetFuncColor(2)
	style.SetFuncStyle(1)
	style.SetFuncWidth(1)

	#For the date
	style.SetOptDate(0)

	# For the statistics box
	style.SetOptFile(0)
	style.SetOptStat("")
	# To display the mean and RMS
	#style.SetOptStat("mr") 
	style.SetStatColor(kWhite)
	style.SetStatFont(TEXTFONT)
	style.SetStatFontSize(TEXTSIZE)
	style.SetStatTextColor(1)
	style.SetStatFormat("6.4g")
	style.SetStatBorderSize(1)
	style.SetStatH(0.2)
	style.SetStatW(0.3)

	# Margins
	style.SetPadTopMargin(0.05)
	style.SetPadBottomMargin(0.16)
	style.SetPadLeftMargin(0.16)
	style.SetPadRightMargin(0.16)

	# For the global title
	style.SetOptTitle(0)
	style.SetTitleFont(TEXTFONT)
	style.SetTitleColor(1)
	style.SetTitleTextColor(1)
	style.SetTitleFillColor(10)
	style.SetTitleFontSize(TEXTSIZE*1.1)

	# For the axis titles
	style.SetTitleColor(1, "XYZ")
	style.SetTitleFont(TEXTFONT, "XYZ")
	style.SetTitleSize(TEXTSIZE*1.2, "XYZ") # 0,05
	style.SetTitleXOffset(1.25) # 0.9
	style.SetTitleYOffset(1.25) # 1.25

	# For the axis labels
	style.SetLabelColor(1, "XYZ")
	style.SetLabelFont(TEXTFONT, "XYZ")
	style.SetLabelOffset(0.006, "XYZ")
	style.SetLabelSize(TEXTSIZE*1.2, "XYZ")

	# For the axis
	style.SetAxisColor(1, "XYZ")
	style.SetStripDecimals(kTRUE)
	style.SetTickLength(0.03, "XYZ")
	style.SetNdivisions(505, "XYZ")

	# To get tick marks on the opposite side of the frame
	style.SetPadTickX(1)  
	style.SetPadTickY(1)

	# Change for log plots
	style.SetOptLogx(0)
	style.SetOptLogy(0)
	style.SetOptLogz(0)

	# Postscript options
	style.SetPaperSize(20.,20.)

	style.cd()
# -----------------------------------------------------------------------------
#  Define variables to be read
# -----------------------------------------------------------------------------
GenRunInfoProduct_crossSection	= Double()
GenRunInfoProduct_filterEfficiency	= Double()
GenRunInfoProduct_internalXSec_value	= Double()
PileupSummaryInfo_getBunchCrossing	= vector("int")(10)
PileupSummaryInfo_getPU_NumInteractions	= vector("int")(10)
PileupSummaryInfo_getTrueNumInteractions	= vector("float")(10)
edmEventHelper_bunchCrossing	= Long()
edmEventHelper_event	= Long()
edmEventHelper_isRealData	= Long()
edmEventHelper_luminosityBlock	= Long()
edmEventHelper_orbitNumber	= Long()
edmEventHelper_run	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v1	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v10	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v11	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v12	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v13	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v14	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v15	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v16	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v2	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v3	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v4	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v5	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v6	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v7	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v8	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v9	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v1	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v10	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v11	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v12	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v13	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v14	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v15	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v16	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v2	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v3	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v4	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v5	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v6	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v7	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v8	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v9	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v1	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v10	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v11	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v12	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v13	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v14	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v2	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v3	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v4	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v5	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v6	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v7	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v8	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v9	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v1	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v10	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v11	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v2	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v3	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v4	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v5	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v6	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v7	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v8	= Long()
edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v9	= Long()
edmTriggerResultsHelper_prescale_HLT_PFHT350_PFMET100_v1	= Long()
edmTriggerResultsHelper_prescale_HLT_PFHT350_PFMET100_v2	= Long()
edmTriggerResultsHelper_prescale_HLT_PFHT350_PFMET100_v3	= Long()
edmTriggerResultsHelper_prescale_HLT_PFNoPUHT350_PFMET100_v1	= Long()
edmTriggerResultsHelper_prescale_HLT_PFNoPUHT350_PFMET100_v2	= Long()
edmTriggerResultsHelper_prescale_HLT_PFNoPUHT350_PFMET100_v3	= Long()
edmTriggerResultsHelper_prescale_HLT_PFNoPUHT350_PFMET100_v4	= Long()
edmTriggerResultsHelper_prescale_HLT_PFNoPUHT350_PFMET100_v5	= Long()
edmTriggerResultsHelper_value_HLT_PFHT350_PFMET100_v1	= Long()
edmTriggerResultsHelper_value_HLT_PFHT350_PFMET100_v2	= Long()
edmTriggerResultsHelper_value_HLT_PFHT350_PFMET100_v3	= Long()
edmTriggerResultsHelper_value_HLT_PFNoPUHT350_PFMET100_v1	= Long()
edmTriggerResultsHelper_value_HLT_PFNoPUHT350_PFMET100_v2	= Long()
edmTriggerResultsHelper_value_HLT_PFNoPUHT350_PFMET100_v3	= Long()
edmTriggerResultsHelper_value_HLT_PFNoPUHT350_PFMET100_v4	= Long()
edmTriggerResultsHelper_value_HLT_PFNoPUHT350_PFMET100_v5	= Long()
nPileupSummaryInfo	= Long()
npatElectron	= Long()
npatJet	= Long()
npatMET	= Long()
npatMET2	= Long()
npatMuon	= Long()
npatTau	= Long()
npatTau_signalPFChargedHadrCands	= vector("size_t")(200)
nrecoGenParticleHelper	= Long()
nrecoGenParticleHelperPlus	= Long()
nrecoGsfElectron	= Long()
nrecoPFMET	= Long()
nrecoPFMET1	= Long()
nrecoVertex	= Long()
patElectron_deltaEtaSuperClusterTrackAtVtx	= vector("float")(200)
patElectron_deltaPhiSuperClusterTrackAtVtx	= vector("float")(200)
patElectron_dr04EcalRecHitSumEt	= vector("float")(200)
patElectron_dr04TkSumPt	= vector("float")(200)
patElectron_eSuperClusterOverP	= vector("float")(200)
patElectron_energy	= vector("double")(200)
patElectron_et	= vector("double")(200)
patElectron_eta	= vector("double")(200)
patElectron_gsfTrack_d0	= vector("double")(200)
patElectron_gsfTrack_dxy	= vector("double")(200)
patElectron_gsfTrack_dz	= vector("double")(200)
patElectron_hadronicOverEm	= vector("float")(200)
patElectron_p	= vector("double")(200)
patElectron_phi	= vector("double")(200)
patElectron_pt	= vector("double")(200)
patElectron_px	= vector("double")(200)
patElectron_py	= vector("double")(200)
patElectron_pz	= vector("double")(200)
patElectron_scE1x5	= vector("float")(200)
patElectron_scE2x5Max	= vector("float")(200)
patElectron_scE5x5	= vector("float")(200)
patElectron_sigmaIetaIeta	= vector("float")(200)
patJet_HFEMEnergy	= vector("float")(200)
patJet_HFEMEnergyFraction	= vector("float")(200)
patJet_HFEMMultiplicity	= vector("int")(200)
patJet_HFHadronEnergy	= vector("float")(200)
patJet_HFHadronEnergyFraction	= vector("float")(200)
patJet_HFHadronMultiplicity	= vector("int")(200)
patJet_bDiscriminator_combinedInclusiveSecondaryVertexBJetTags	= vector("float")(200)
patJet_bDiscriminator_combinedMVABJetTags	= vector("float")(200)
patJet_bDiscriminator_combinedSecondaryVertexBJetTags	= vector("float")(200)
patJet_bDiscriminator_combinedSecondaryVertexMVABJetTags	= vector("float")(200)
patJet_bDiscriminator_impactParameterTagInfos	= vector("float")(200)
patJet_bDiscriminator_inclusiveSecondaryVertexFinderTagInfos	= vector("float")(200)
patJet_bDiscriminator_jetBProbabilityBJetTags	= vector("float")(200)
patJet_bDiscriminator_jetProbabilityBJetTags	= vector("float")(200)
patJet_bDiscriminator_negativeTrackCountingHighEffJetTags	= vector("float")(200)
patJet_bDiscriminator_negativeTrackCountingHighPurJetTags	= vector("float")(200)
patJet_bDiscriminator_secondaryVertexNegativeTagInfos	= vector("float")(200)
patJet_bDiscriminator_secondaryVertexTagInfos	= vector("float")(200)
patJet_bDiscriminator_simpleSecondaryVertexHighEffBJetTags	= vector("float")(200)
patJet_bDiscriminator_simpleSecondaryVertexHighPurBJetTags	= vector("float")(200)
patJet_bDiscriminator_simpleSecondaryVertexNegativeHighEffBJetTags	= vector("float")(200)
patJet_bDiscriminator_simpleSecondaryVertexNegativeHighPurBJetTags	= vector("float")(200)
patJet_bDiscriminator_softElectronTagInfos	= vector("float")(200)
patJet_bDiscriminator_softMuonBJetTags	= vector("float")(200)
patJet_bDiscriminator_softMuonByIP3dBJetTags	= vector("float")(200)
patJet_bDiscriminator_softMuonByPtBJetTags	= vector("float")(200)
patJet_bDiscriminator_softMuonTagInfos	= vector("float")(200)
patJet_bDiscriminator_trackCountingHighEffBJetTags	= vector("float")(200)
patJet_bDiscriminator_trackCountingHighPurBJetTags	= vector("float")(200)
patJet_charge	= vector("int")(200)
patJet_chargedEmEnergyFraction	= vector("float")(200)
patJet_chargedHadronEnergyFraction	= vector("float")(200)
patJet_chargedHadronMultiplicity	= vector("int")(200)
patJet_chargedMultiplicity	= vector("int")(200)
patJet_electronEnergy	= vector("float")(200)
patJet_electronEnergyFraction	= vector("float")(200)
patJet_electronMultiplicity	= vector("int")(200)
patJet_energy	= vector("double")(200)
patJet_et	= vector("double")(200)
patJet_eta	= vector("double")(200)
patJet_muonEnergy	= vector("float")(200)
patJet_muonEnergyFraction	= vector("float")(200)
patJet_neutralEmEnergyFraction	= vector("float")(200)
patJet_neutralHadronEnergy	= vector("float")(200)
patJet_neutralHadronEnergyFraction	= vector("float")(200)
patJet_neutralHadronMultiplicity	= vector("int")(200)
patJet_numberOfDaughters	= vector("size_t")(200)
patJet_p	= vector("double")(200)
patJet_phi	= vector("double")(200)
patJet_photonEnergy	= vector("float")(200)
patJet_photonEnergyFraction	= vector("float")(200)
patJet_photonMultiplicity	= vector("int")(200)
patJet_pt	= vector("double")(200)
patJet_px	= vector("double")(200)
patJet_py	= vector("double")(200)
patJet_pz	= vector("double")(200)
patMET2_energy	= vector("double")(200)
patMET2_et	= vector("double")(200)
patMET2_eta	= vector("double")(200)
patMET2_p	= vector("double")(200)
patMET2_phi	= vector("double")(200)
patMET2_pt	= vector("double")(200)
patMET2_px	= vector("double")(200)
patMET2_py	= vector("double")(200)
patMET2_pz	= vector("double")(200)
patMET_energy	= vector("double")(200)
patMET_et	= vector("double")(200)
patMET_eta	= vector("double")(200)
patMET_p	= vector("double")(200)
patMET_phi	= vector("double")(200)
patMET_pt	= vector("double")(200)
patMET_px	= vector("double")(200)
patMET_py	= vector("double")(200)
patMET_pz	= vector("double")(200)
patMuon_energy	= vector("double")(200)
patMuon_et	= vector("double")(200)
patMuon_eta	= vector("double")(200)
patMuon_globalTrack_hitPattern_numberOfValidMuonHits	= vector("int")(200)
patMuon_globalTrack_normalizedChi2	= vector("double")(200)
patMuon_innerTrack_dxy	= vector("double")(200)
patMuon_innerTrack_dz	= vector("double")(200)
patMuon_innerTrack_hitPattern_numberOfValidPixelHits	= vector("int")(200)
patMuon_innerTrack_hitPattern_pixelLayersWithMeasurement	= vector("int")(200)
patMuon_innerTrack_normalizedChi2	= vector("double")(200)
patMuon_isGlobalMuon	= vector("int")(200)
patMuon_isPFMuon	= vector("int")(200)
patMuon_isTrackerMuon	= vector("int")(200)
patMuon_muonBestTrack_dxy	= vector("double")(200)
patMuon_muonBestTrack_dz	= vector("double")(200)
patMuon_numberOfMatchedStations	= vector("int")(200)
patMuon_p	= vector("double")(200)
patMuon_pfIsolationR03_sumChargedHadronPt	= vector("float")(200)
patMuon_pfIsolationR03_sumChargedParticlePt	= vector("float")(200)
patMuon_pfIsolationR03_sumNeutralHadronEt	= vector("float")(200)
patMuon_pfIsolationR03_sumNeutralHadronEtHighThreshold	= vector("float")(200)
patMuon_pfIsolationR03_sumPUPt	= vector("float")(200)
patMuon_pfIsolationR03_sumPhotonEt	= vector("float")(200)
patMuon_pfIsolationR03_sumPhotonEtHighThreshold	= vector("float")(200)
patMuon_pfIsolationR04_sumChargedHadronPt	= vector("float")(200)
patMuon_pfIsolationR04_sumChargedParticlePt	= vector("float")(200)
patMuon_pfIsolationR04_sumNeutralHadronEt	= vector("float")(200)
patMuon_pfIsolationR04_sumNeutralHadronEtHighThreshold	= vector("float")(200)
patMuon_pfIsolationR04_sumPUPt	= vector("float")(200)
patMuon_pfIsolationR04_sumPhotonEt	= vector("float")(200)
patMuon_pfIsolationR04_sumPhotonEtHighThreshold	= vector("float")(200)
patMuon_phi	= vector("double")(200)
patMuon_pt	= vector("double")(200)
patMuon_px	= vector("double")(200)
patMuon_py	= vector("double")(200)
patMuon_pz	= vector("double")(200)
patTau_charge	= vector("int")(200)
patTau_energy	= vector("double")(200)
patTau_et	= vector("double")(200)
patTau_eta	= vector("double")(200)
patTau_leadPFChargedHadrCand_energy	= vector("double")(200)
patTau_leadPFChargedHadrCand_et	= vector("double")(200)
patTau_leadPFChargedHadrCand_eta	= vector("double")(200)
patTau_leadPFChargedHadrCand_mass	= vector("double")(200)
patTau_leadPFChargedHadrCand_massSqr	= vector("double")(200)
patTau_leadPFChargedHadrCand_mt	= vector("double")(200)
patTau_leadPFChargedHadrCand_mtSqr	= vector("double")(200)
patTau_leadPFChargedHadrCand_p	= vector("double")(200)
patTau_leadPFChargedHadrCand_phi	= vector("double")(200)
patTau_leadPFChargedHadrCand_pt	= vector("double")(200)
patTau_leadPFChargedHadrCand_px	= vector("double")(200)
patTau_leadPFChargedHadrCand_py	= vector("double")(200)
patTau_leadPFChargedHadrCand_pz	= vector("double")(200)
patTau_leadPFChargedHadrCand_rapidity	= vector("double")(200)
patTau_leadPFChargedHadrCand_theta	= vector("double")(200)
patTau_leadPFChargedHadrCand_y	= vector("double")(200)
patTau_p	= vector("double")(200)
patTau_phi	= vector("double")(200)
patTau_pt	= vector("double")(200)
patTau_px	= vector("double")(200)
patTau_py	= vector("double")(200)
patTau_pz	= vector("double")(200)
patTau_tauID_againstElectronDeadECAL	= vector("float")(200)
patTau_tauID_againstElectronLoose	= vector("float")(200)
patTau_tauID_againstElectronLooseMVA5	= vector("float")(200)
patTau_tauID_againstElectronMVA5category	= vector("float")(200)
patTau_tauID_againstElectronMVA5raw	= vector("float")(200)
patTau_tauID_againstElectronMedium	= vector("float")(200)
patTau_tauID_againstElectronMediumMVA5	= vector("float")(200)
patTau_tauID_againstElectronTight	= vector("float")(200)
patTau_tauID_againstElectronTightMVA5	= vector("float")(200)
patTau_tauID_againstElectronVLooseMVA5	= vector("float")(200)
patTau_tauID_againstElectronVTightMVA5	= vector("float")(200)
patTau_tauID_againstMuonLoose	= vector("float")(200)
patTau_tauID_againstMuonLoose2	= vector("float")(200)
patTau_tauID_againstMuonLoose3	= vector("float")(200)
patTau_tauID_againstMuonLooseMVA	= vector("float")(200)
patTau_tauID_againstMuonMVAraw	= vector("float")(200)
patTau_tauID_againstMuonMedium	= vector("float")(200)
patTau_tauID_againstMuonMedium2	= vector("float")(200)
patTau_tauID_againstMuonMediumMVA	= vector("float")(200)
patTau_tauID_againstMuonTight	= vector("float")(200)
patTau_tauID_againstMuonTight2	= vector("float")(200)
patTau_tauID_againstMuonTight3	= vector("float")(200)
patTau_tauID_againstMuonTightMVA	= vector("float")(200)
patTau_tauID_byCombinedIsolationDeltaBetaCorrRaw	= vector("float")(200)
patTau_tauID_byCombinedIsolationDeltaBetaCorrRaw3Hits	= vector("float")(200)
patTau_tauID_byIsolationMVA3newDMwLTraw	= vector("float")(200)
patTau_tauID_byIsolationMVA3newDMwoLTraw	= vector("float")(200)
patTau_tauID_byIsolationMVA3oldDMwLTraw	= vector("float")(200)
patTau_tauID_byIsolationMVA3oldDMwoLTraw	= vector("float")(200)
patTau_tauID_byLooseCombinedIsolationDeltaBetaCorr	= vector("float")(200)
patTau_tauID_byLooseCombinedIsolationDeltaBetaCorr3Hits	= vector("float")(200)
patTau_tauID_byLooseIsolation	= vector("float")(200)
patTau_tauID_byLooseIsolationMVA3newDMwLT	= vector("float")(200)
patTau_tauID_byLooseIsolationMVA3newDMwoLT	= vector("float")(200)
patTau_tauID_byLooseIsolationMVA3oldDMwLT	= vector("float")(200)
patTau_tauID_byLooseIsolationMVA3oldDMwoLT	= vector("float")(200)
patTau_tauID_byMediumCombinedIsolationDeltaBetaCorr	= vector("float")(200)
patTau_tauID_byMediumCombinedIsolationDeltaBetaCorr3Hits	= vector("float")(200)
patTau_tauID_byMediumIsolationMVA3newDMwLT	= vector("float")(200)
patTau_tauID_byMediumIsolationMVA3newDMwoLT	= vector("float")(200)
patTau_tauID_byMediumIsolationMVA3oldDMwLT	= vector("float")(200)
patTau_tauID_byMediumIsolationMVA3oldDMwoLT	= vector("float")(200)
patTau_tauID_byTightCombinedIsolationDeltaBetaCorr	= vector("float")(200)
patTau_tauID_byTightCombinedIsolationDeltaBetaCorr3Hits	= vector("float")(200)
patTau_tauID_byTightIsolationMVA3newDMwLT	= vector("float")(200)
patTau_tauID_byTightIsolationMVA3newDMwoLT	= vector("float")(200)
patTau_tauID_byTightIsolationMVA3oldDMwLT	= vector("float")(200)
patTau_tauID_byTightIsolationMVA3oldDMwoLT	= vector("float")(200)
patTau_tauID_byVLooseCombinedIsolationDeltaBetaCorr	= vector("float")(200)
patTau_tauID_byVLooseIsolationMVA3newDMwLT	= vector("float")(200)
patTau_tauID_byVLooseIsolationMVA3newDMwoLT	= vector("float")(200)
patTau_tauID_byVLooseIsolationMVA3oldDMwLT	= vector("float")(200)
patTau_tauID_byVLooseIsolationMVA3oldDMwoLT	= vector("float")(200)
patTau_tauID_byVTightIsolationMVA3newDMwLT	= vector("float")(200)
patTau_tauID_byVTightIsolationMVA3newDMwoLT	= vector("float")(200)
patTau_tauID_byVTightIsolationMVA3oldDMwLT	= vector("float")(200)
patTau_tauID_byVTightIsolationMVA3oldDMwoLT	= vector("float")(200)
patTau_tauID_byVVTightIsolationMVA3newDMwLT	= vector("float")(200)
patTau_tauID_byVVTightIsolationMVA3newDMwoLT	= vector("float")(200)
patTau_tauID_byVVTightIsolationMVA3oldDMwLT	= vector("float")(200)
patTau_tauID_byVVTightIsolationMVA3oldDMwoLT	= vector("float")(200)
patTau_tauID_chargedIsoPtSum	= vector("float")(200)
patTau_tauID_decayModeFinding	= vector("float")(200)
patTau_tauID_decayModeFindingNewDMs	= vector("float")(200)
patTau_tauID_decayModeFindingOldDMs	= vector("float")(200)
patTau_tauID_neutralIsoPtSum	= vector("float")(200)
patTau_tauID_puCorrPtSum	= vector("float")(200)
patTau_vx	= vector("double")(200)
patTau_vy	= vector("double")(200)
patTau_vz	= vector("double")(200)
recoBeamSpot_x0	= Double()
recoBeamSpot_y0	= Double()
recoBeamSpot_z0	= Double()
recoGenParticleHelperPlus_charge	= vector("int")(100)
recoGenParticleHelperPlus_eta	= vector("double")(100)
recoGenParticleHelperPlus_firstDaughter	= vector("int")(100)
recoGenParticleHelperPlus_firstMother	= vector("int")(100)
recoGenParticleHelperPlus_lastDaughter	= vector("int")(100)
recoGenParticleHelperPlus_lastMother	= vector("int")(100)
recoGenParticleHelperPlus_mass	= vector("double")(100)
recoGenParticleHelperPlus_pdgId	= vector("int")(100)
recoGenParticleHelperPlus_phi	= vector("double")(100)
recoGenParticleHelperPlus_pt	= vector("double")(100)
recoGenParticleHelperPlus_status	= vector("int")(100)
recoGenParticleHelper_charge	= vector("int")(100)
recoGenParticleHelper_eta	= vector("double")(100)
recoGenParticleHelper_firstDaughter	= vector("int")(100)
recoGenParticleHelper_firstMother	= vector("int")(100)
recoGenParticleHelper_lastDaughter	= vector("int")(100)
recoGenParticleHelper_lastMother	= vector("int")(100)
recoGenParticleHelper_mass	= vector("double")(100)
recoGenParticleHelper_pdgId	= vector("int")(100)
recoGenParticleHelper_phi	= vector("double")(100)
recoGenParticleHelper_pt	= vector("double")(100)
recoGenParticleHelper_status	= vector("int")(100)
recoGsfElectron_deltaEtaSuperClusterTrackAtVtx	= vector("float")(200)
recoGsfElectron_deltaPhiSuperClusterTrackAtVtx	= vector("float")(200)
recoGsfElectron_dr04EcalRecHitSumEt	= vector("float")(200)
recoGsfElectron_dr04TkSumPt	= vector("float")(200)
recoGsfElectron_eSuperClusterOverP	= vector("float")(200)
recoGsfElectron_energy	= vector("double")(200)
recoGsfElectron_et	= vector("double")(200)
recoGsfElectron_eta	= vector("double")(200)
recoGsfElectron_gsfTrack_d0	= vector("double")(200)
recoGsfElectron_gsfTrack_dxy	= vector("double")(200)
recoGsfElectron_gsfTrack_dz	= vector("double")(200)
recoGsfElectron_hadronicOverEm	= vector("float")(200)
recoGsfElectron_p	= vector("double")(200)
recoGsfElectron_phi	= vector("double")(200)
recoGsfElectron_pt	= vector("double")(200)
recoGsfElectron_px	= vector("double")(200)
recoGsfElectron_py	= vector("double")(200)
recoGsfElectron_pz	= vector("double")(200)
recoGsfElectron_scE1x5	= vector("float")(200)
recoGsfElectron_scE2x5Max	= vector("float")(200)
recoGsfElectron_scE5x5	= vector("float")(200)
recoGsfElectron_sigmaIetaIeta	= vector("float")(200)
recoPFMET1_energy	= vector("double")(200)
recoPFMET1_et	= vector("double")(200)
recoPFMET1_eta	= vector("double")(200)
recoPFMET1_p	= vector("double")(200)
recoPFMET1_phi	= vector("double")(200)
recoPFMET1_pt	= vector("double")(200)
recoPFMET1_px	= vector("double")(200)
recoPFMET1_py	= vector("double")(200)
recoPFMET1_pz	= vector("double")(200)
recoPFMET_energy	= vector("double")(200)
recoPFMET_et	= vector("double")(200)
recoPFMET_eta	= vector("double")(200)
recoPFMET_p	= vector("double")(200)
recoPFMET_phi	= vector("double")(200)
recoPFMET_pt	= vector("double")(200)
recoPFMET_px	= vector("double")(200)
recoPFMET_py	= vector("double")(200)
recoPFMET_pz	= vector("double")(200)
recoVertex_isFake	= vector("int")(200)
recoVertex_ndof	= vector("double")(200)
recoVertex_x	= vector("double")(200)
recoVertex_y	= vector("double")(200)
recoVertex_z	= vector("double")(200)

stream.select("GenRunInfoProduct_generator.crossSection", GenRunInfoProduct_crossSection)
stream.select("GenRunInfoProduct_generator.filterEfficiency", GenRunInfoProduct_filterEfficiency)
stream.select("GenRunInfoProduct_generator.internalXSec_value", GenRunInfoProduct_internalXSec_value)
stream.select("PileupSummaryInfo_addPileupInfo.getBunchCrossing", PileupSummaryInfo_getBunchCrossing)
stream.select("PileupSummaryInfo_addPileupInfo.getPU_NumInteractions", PileupSummaryInfo_getPU_NumInteractions)
stream.select("PileupSummaryInfo_addPileupInfo.getTrueNumInteractions", PileupSummaryInfo_getTrueNumInteractions)
stream.select("edmEventHelper_info.bunchCrossing", edmEventHelper_bunchCrossing)
stream.select("edmEventHelper_info.event", edmEventHelper_event)
stream.select("edmEventHelper_info.isRealData", edmEventHelper_isRealData)
stream.select("edmEventHelper_info.luminosityBlock", edmEventHelper_luminosityBlock)
stream.select("edmEventHelper_info.orbitNumber", edmEventHelper_orbitNumber)
stream.select("edmEventHelper_info.run", edmEventHelper_run)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v1", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v1)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v10", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v10)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v11", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v11)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v12", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v12)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v13", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v13)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v14", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v14)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v15", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v15)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v16", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v16)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v2", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v2)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v3", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v3)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v4", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v4)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v5", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v5)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v6", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v6)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v7", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v7)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v8", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v8)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu24_eta2p1_v9", edmTriggerResultsHelper_prescale_HLT_IsoMu24_eta2p1_v9)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v1", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v1)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v10", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v10)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v11", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v11)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v12", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v12)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v13", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v13)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v14", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v14)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v15", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v15)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v16", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v16)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v2", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v2)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v3", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v3)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v4", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v4)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v5", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v5)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v6", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v6)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v7", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v7)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v8", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v8)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu30_eta2p1_v9", edmTriggerResultsHelper_prescale_HLT_IsoMu30_eta2p1_v9)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v1", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v1)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v10", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v10)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v11", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v11)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v12", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v12)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v13", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v13)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v14", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v14)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v2", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v2)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v3", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v3)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v4", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v4)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v5", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v5)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v6", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v6)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v7", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v7)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v8", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v8)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu34_eta2p1_v9", edmTriggerResultsHelper_prescale_HLT_IsoMu34_eta2p1_v9)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v1", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v1)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v10", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v10)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v11", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v11)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v2", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v2)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v3", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v3)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v4", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v4)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v5", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v5)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v6", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v6)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v7", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v7)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v8", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v8)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_IsoMu40_eta2p1_v9", edmTriggerResultsHelper_prescale_HLT_IsoMu40_eta2p1_v9)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_PFHT350_PFMET100_v1", edmTriggerResultsHelper_prescale_HLT_PFHT350_PFMET100_v1)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_PFHT350_PFMET100_v2", edmTriggerResultsHelper_prescale_HLT_PFHT350_PFMET100_v2)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_PFHT350_PFMET100_v3", edmTriggerResultsHelper_prescale_HLT_PFHT350_PFMET100_v3)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_PFNoPUHT350_PFMET100_v1", edmTriggerResultsHelper_prescale_HLT_PFNoPUHT350_PFMET100_v1)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_PFNoPUHT350_PFMET100_v2", edmTriggerResultsHelper_prescale_HLT_PFNoPUHT350_PFMET100_v2)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_PFNoPUHT350_PFMET100_v3", edmTriggerResultsHelper_prescale_HLT_PFNoPUHT350_PFMET100_v3)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_PFNoPUHT350_PFMET100_v4", edmTriggerResultsHelper_prescale_HLT_PFNoPUHT350_PFMET100_v4)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.prescale_HLT_PFNoPUHT350_PFMET100_v5", edmTriggerResultsHelper_prescale_HLT_PFNoPUHT350_PFMET100_v5)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.value_HLT_PFHT350_PFMET100_v1", edmTriggerResultsHelper_value_HLT_PFHT350_PFMET100_v1)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.value_HLT_PFHT350_PFMET100_v2", edmTriggerResultsHelper_value_HLT_PFHT350_PFMET100_v2)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.value_HLT_PFHT350_PFMET100_v3", edmTriggerResultsHelper_value_HLT_PFHT350_PFMET100_v3)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.value_HLT_PFNoPUHT350_PFMET100_v1", edmTriggerResultsHelper_value_HLT_PFNoPUHT350_PFMET100_v1)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.value_HLT_PFNoPUHT350_PFMET100_v2", edmTriggerResultsHelper_value_HLT_PFNoPUHT350_PFMET100_v2)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.value_HLT_PFNoPUHT350_PFMET100_v3", edmTriggerResultsHelper_value_HLT_PFNoPUHT350_PFMET100_v3)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.value_HLT_PFNoPUHT350_PFMET100_v4", edmTriggerResultsHelper_value_HLT_PFNoPUHT350_PFMET100_v4)
stream.select("edmTriggerResultsHelper_TriggerResults_HLT.value_HLT_PFNoPUHT350_PFMET100_v5", edmTriggerResultsHelper_value_HLT_PFNoPUHT350_PFMET100_v5)
stream.select("nPileupSummaryInfo_addPileupInfo", nPileupSummaryInfo)
stream.select("npatElectron_patElectrons", npatElectron)
stream.select("npatJet_selectedPatJets", npatJet)
stream.select("npatMET_patMETs", npatMET)
stream.select("npatMET_patPfMetT0pcT1Txy", npatMET2)
stream.select("npatMuon_patMuons", npatMuon)
stream.select("npatTauHelper_patTaus", npatTau)
stream.select("patTauHelper_patTaus.signalPFChargedHadrCands_size", npatTau_signalPFChargedHadrCands)
stream.select("nrecoGenParticleHelper_genParticles", nrecoGenParticleHelper)
stream.select("nrecoGenParticleHelperPlus_genParticles", nrecoGenParticleHelperPlus)
stream.select("nrecoGsfElectron_gsfElectrons", nrecoGsfElectron)
stream.select("nrecoPFMET_pfType1CorrectedMet", nrecoPFMET)
stream.select("nrecoPFMET_pfType1p2CorrectedMet", nrecoPFMET1)
stream.select("nrecoVertex_offlinePrimaryVertices", nrecoVertex)
stream.select("patElectron_patElectrons.deltaEtaSuperClusterTrackAtVtx", patElectron_deltaEtaSuperClusterTrackAtVtx)
stream.select("patElectron_patElectrons.deltaPhiSuperClusterTrackAtVtx", patElectron_deltaPhiSuperClusterTrackAtVtx)
stream.select("patElectron_patElectrons.dr04EcalRecHitSumEt", patElectron_dr04EcalRecHitSumEt)
stream.select("patElectron_patElectrons.dr04TkSumPt", patElectron_dr04TkSumPt)
stream.select("patElectron_patElectrons.eSuperClusterOverP", patElectron_eSuperClusterOverP)
stream.select("patElectron_patElectrons.energy", patElectron_energy)
stream.select("patElectron_patElectrons.et", patElectron_et)
stream.select("patElectron_patElectrons.eta", patElectron_eta)
stream.select("patElectron_patElectrons.gsfTrack_d0", patElectron_gsfTrack_d0)
stream.select("patElectron_patElectrons.gsfTrack_dxy", patElectron_gsfTrack_dxy)
stream.select("patElectron_patElectrons.gsfTrack_dz", patElectron_gsfTrack_dz)
stream.select("patElectron_patElectrons.hadronicOverEm", patElectron_hadronicOverEm)
stream.select("patElectron_patElectrons.p", patElectron_p)
stream.select("patElectron_patElectrons.phi", patElectron_phi)
stream.select("patElectron_patElectrons.pt", patElectron_pt)
stream.select("patElectron_patElectrons.px", patElectron_px)
stream.select("patElectron_patElectrons.py", patElectron_py)
stream.select("patElectron_patElectrons.pz", patElectron_pz)
stream.select("patElectron_patElectrons.scE1x5", patElectron_scE1x5)
stream.select("patElectron_patElectrons.scE2x5Max", patElectron_scE2x5Max)
stream.select("patElectron_patElectrons.scE5x5", patElectron_scE5x5)
stream.select("patElectron_patElectrons.sigmaIetaIeta", patElectron_sigmaIetaIeta)
stream.select("patJet_selectedPatJets.HFEMEnergy", patJet_HFEMEnergy)
stream.select("patJet_selectedPatJets.HFEMEnergyFraction", patJet_HFEMEnergyFraction)
stream.select("patJet_selectedPatJets.HFEMMultiplicity", patJet_HFEMMultiplicity)
stream.select("patJet_selectedPatJets.HFHadronEnergy", patJet_HFHadronEnergy)
stream.select("patJet_selectedPatJets.HFHadronEnergyFraction", patJet_HFHadronEnergyFraction)
stream.select("patJet_selectedPatJets.HFHadronMultiplicity", patJet_HFHadronMultiplicity)
stream.select("patJet_selectedPatJets.bDiscriminator_combinedInclusiveSecondaryVertexBJetTags", patJet_bDiscriminator_combinedInclusiveSecondaryVertexBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_combinedMVABJetTags", patJet_bDiscriminator_combinedMVABJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_combinedSecondaryVertexBJetTags", patJet_bDiscriminator_combinedSecondaryVertexBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_combinedSecondaryVertexMVABJetTags", patJet_bDiscriminator_combinedSecondaryVertexMVABJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_impactParameterTagInfos", patJet_bDiscriminator_impactParameterTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_inclusiveSecondaryVertexFinderTagInfos", patJet_bDiscriminator_inclusiveSecondaryVertexFinderTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_jetBProbabilityBJetTags", patJet_bDiscriminator_jetBProbabilityBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_jetProbabilityBJetTags", patJet_bDiscriminator_jetProbabilityBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_negativeTrackCountingHighEffJetTags", patJet_bDiscriminator_negativeTrackCountingHighEffJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_negativeTrackCountingHighPurJetTags", patJet_bDiscriminator_negativeTrackCountingHighPurJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_secondaryVertexNegativeTagInfos", patJet_bDiscriminator_secondaryVertexNegativeTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_secondaryVertexTagInfos", patJet_bDiscriminator_secondaryVertexTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_simpleSecondaryVertexHighEffBJetTags", patJet_bDiscriminator_simpleSecondaryVertexHighEffBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_simpleSecondaryVertexHighPurBJetTags", patJet_bDiscriminator_simpleSecondaryVertexHighPurBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_simpleSecondaryVertexNegativeHighEffBJetTags", patJet_bDiscriminator_simpleSecondaryVertexNegativeHighEffBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_simpleSecondaryVertexNegativeHighPurBJetTags", patJet_bDiscriminator_simpleSecondaryVertexNegativeHighPurBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_softElectronTagInfos", patJet_bDiscriminator_softElectronTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_softMuonBJetTags", patJet_bDiscriminator_softMuonBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_softMuonByIP3dBJetTags", patJet_bDiscriminator_softMuonByIP3dBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_softMuonByPtBJetTags", patJet_bDiscriminator_softMuonByPtBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_softMuonTagInfos", patJet_bDiscriminator_softMuonTagInfos)
stream.select("patJet_selectedPatJets.bDiscriminator_trackCountingHighEffBJetTags", patJet_bDiscriminator_trackCountingHighEffBJetTags)
stream.select("patJet_selectedPatJets.bDiscriminator_trackCountingHighPurBJetTags", patJet_bDiscriminator_trackCountingHighPurBJetTags)
stream.select("patJet_selectedPatJets.charge", patJet_charge)
stream.select("patJet_selectedPatJets.chargedEmEnergyFraction", patJet_chargedEmEnergyFraction)
stream.select("patJet_selectedPatJets.chargedHadronEnergyFraction", patJet_chargedHadronEnergyFraction)
stream.select("patJet_selectedPatJets.chargedHadronMultiplicity", patJet_chargedHadronMultiplicity)
stream.select("patJet_selectedPatJets.chargedMultiplicity", patJet_chargedMultiplicity)
stream.select("patJet_selectedPatJets.electronEnergy", patJet_electronEnergy)
stream.select("patJet_selectedPatJets.electronEnergyFraction", patJet_electronEnergyFraction)
stream.select("patJet_selectedPatJets.electronMultiplicity", patJet_electronMultiplicity)
stream.select("patJet_selectedPatJets.energy", patJet_energy)
stream.select("patJet_selectedPatJets.et", patJet_et)
stream.select("patJet_selectedPatJets.eta", patJet_eta)
stream.select("patJet_selectedPatJets.muonEnergy", patJet_muonEnergy)
stream.select("patJet_selectedPatJets.muonEnergyFraction", patJet_muonEnergyFraction)
stream.select("patJet_selectedPatJets.neutralEmEnergyFraction", patJet_neutralEmEnergyFraction)
stream.select("patJet_selectedPatJets.neutralHadronEnergy", patJet_neutralHadronEnergy)
stream.select("patJet_selectedPatJets.neutralHadronEnergyFraction", patJet_neutralHadronEnergyFraction)
stream.select("patJet_selectedPatJets.neutralHadronMultiplicity", patJet_neutralHadronMultiplicity)
stream.select("patJet_selectedPatJets.numberOfDaughters", patJet_numberOfDaughters)
stream.select("patJet_selectedPatJets.p", patJet_p)
stream.select("patJet_selectedPatJets.phi", patJet_phi)
stream.select("patJet_selectedPatJets.photonEnergy", patJet_photonEnergy)
stream.select("patJet_selectedPatJets.photonEnergyFraction", patJet_photonEnergyFraction)
stream.select("patJet_selectedPatJets.photonMultiplicity", patJet_photonMultiplicity)
stream.select("patJet_selectedPatJets.pt", patJet_pt)
stream.select("patJet_selectedPatJets.px", patJet_px)
stream.select("patJet_selectedPatJets.py", patJet_py)
stream.select("patJet_selectedPatJets.pz", patJet_pz)
stream.select("patMET_patPfMetT0pcT1Txy.energy", patMET2_energy)
stream.select("patMET_patPfMetT0pcT1Txy.et", patMET2_et)
stream.select("patMET_patPfMetT0pcT1Txy.eta", patMET2_eta)
stream.select("patMET_patPfMetT0pcT1Txy.p", patMET2_p)
stream.select("patMET_patPfMetT0pcT1Txy.phi", patMET2_phi)
stream.select("patMET_patPfMetT0pcT1Txy.pt", patMET2_pt)
stream.select("patMET_patPfMetT0pcT1Txy.px", patMET2_px)
stream.select("patMET_patPfMetT0pcT1Txy.py", patMET2_py)
stream.select("patMET_patPfMetT0pcT1Txy.pz", patMET2_pz)
stream.select("patMET_patMETs.energy", patMET_energy)
stream.select("patMET_patMETs.et", patMET_et)
stream.select("patMET_patMETs.eta", patMET_eta)
stream.select("patMET_patMETs.p", patMET_p)
stream.select("patMET_patMETs.phi", patMET_phi)
stream.select("patMET_patMETs.pt", patMET_pt)
stream.select("patMET_patMETs.px", patMET_px)
stream.select("patMET_patMETs.py", patMET_py)
stream.select("patMET_patMETs.pz", patMET_pz)
stream.select("patMuon_patMuons.energy", patMuon_energy)
stream.select("patMuon_patMuons.et", patMuon_et)
stream.select("patMuon_patMuons.eta", patMuon_eta)
stream.select("patMuon_patMuons.globalTrack_hitPattern_numberOfValidMuonHits", patMuon_globalTrack_hitPattern_numberOfValidMuonHits)
stream.select("patMuon_patMuons.globalTrack_normalizedChi2", patMuon_globalTrack_normalizedChi2)
stream.select("patMuon_patMuons.innerTrack_dxy", patMuon_innerTrack_dxy)
stream.select("patMuon_patMuons.innerTrack_dz", patMuon_innerTrack_dz)
stream.select("patMuon_patMuons.innerTrack_hitPattern_numberOfValidPixelHits", patMuon_innerTrack_hitPattern_numberOfValidPixelHits)
stream.select("patMuon_patMuons.innerTrack_hitPattern_pixelLayersWithMeasurement", patMuon_innerTrack_hitPattern_pixelLayersWithMeasurement)
stream.select("patMuon_patMuons.innerTrack_normalizedChi2", patMuon_innerTrack_normalizedChi2)
stream.select("patMuon_patMuons.isGlobalMuon", patMuon_isGlobalMuon)
stream.select("patMuon_patMuons.isPFMuon", patMuon_isPFMuon)
stream.select("patMuon_patMuons.isTrackerMuon", patMuon_isTrackerMuon)
stream.select("patMuon_patMuons.muonBestTrack_dxy", patMuon_muonBestTrack_dxy)
stream.select("patMuon_patMuons.muonBestTrack_dz", patMuon_muonBestTrack_dz)
stream.select("patMuon_patMuons.numberOfMatchedStations", patMuon_numberOfMatchedStations)
stream.select("patMuon_patMuons.p", patMuon_p)
stream.select("patMuon_patMuons.pfIsolationR03_sumChargedHadronPt", patMuon_pfIsolationR03_sumChargedHadronPt)
stream.select("patMuon_patMuons.pfIsolationR03_sumChargedParticlePt", patMuon_pfIsolationR03_sumChargedParticlePt)
stream.select("patMuon_patMuons.pfIsolationR03_sumNeutralHadronEt", patMuon_pfIsolationR03_sumNeutralHadronEt)
stream.select("patMuon_patMuons.pfIsolationR03_sumNeutralHadronEtHighThreshold", patMuon_pfIsolationR03_sumNeutralHadronEtHighThreshold)
stream.select("patMuon_patMuons.pfIsolationR03_sumPUPt", patMuon_pfIsolationR03_sumPUPt)
stream.select("patMuon_patMuons.pfIsolationR03_sumPhotonEt", patMuon_pfIsolationR03_sumPhotonEt)
stream.select("patMuon_patMuons.pfIsolationR03_sumPhotonEtHighThreshold", patMuon_pfIsolationR03_sumPhotonEtHighThreshold)
stream.select("patMuon_patMuons.pfIsolationR04_sumChargedHadronPt", patMuon_pfIsolationR04_sumChargedHadronPt)
stream.select("patMuon_patMuons.pfIsolationR04_sumChargedParticlePt", patMuon_pfIsolationR04_sumChargedParticlePt)
stream.select("patMuon_patMuons.pfIsolationR04_sumNeutralHadronEt", patMuon_pfIsolationR04_sumNeutralHadronEt)
stream.select("patMuon_patMuons.pfIsolationR04_sumNeutralHadronEtHighThreshold", patMuon_pfIsolationR04_sumNeutralHadronEtHighThreshold)
stream.select("patMuon_patMuons.pfIsolationR04_sumPUPt", patMuon_pfIsolationR04_sumPUPt)
stream.select("patMuon_patMuons.pfIsolationR04_sumPhotonEt", patMuon_pfIsolationR04_sumPhotonEt)
stream.select("patMuon_patMuons.pfIsolationR04_sumPhotonEtHighThreshold", patMuon_pfIsolationR04_sumPhotonEtHighThreshold)
stream.select("patMuon_patMuons.phi", patMuon_phi)
stream.select("patMuon_patMuons.pt", patMuon_pt)
stream.select("patMuon_patMuons.px", patMuon_px)
stream.select("patMuon_patMuons.py", patMuon_py)
stream.select("patMuon_patMuons.pz", patMuon_pz)
stream.select("patTauHelper_patTaus.charge", patTau_charge)
stream.select("patTauHelper_patTaus.energy", patTau_energy)
stream.select("patTauHelper_patTaus.et", patTau_et)
stream.select("patTauHelper_patTaus.eta", patTau_eta)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_energy", patTau_leadPFChargedHadrCand_energy)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_et", patTau_leadPFChargedHadrCand_et)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_eta", patTau_leadPFChargedHadrCand_eta)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_mass", patTau_leadPFChargedHadrCand_mass)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_massSqr", patTau_leadPFChargedHadrCand_massSqr)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_mt", patTau_leadPFChargedHadrCand_mt)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_mtSqr", patTau_leadPFChargedHadrCand_mtSqr)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_p", patTau_leadPFChargedHadrCand_p)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_phi", patTau_leadPFChargedHadrCand_phi)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_pt", patTau_leadPFChargedHadrCand_pt)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_px", patTau_leadPFChargedHadrCand_px)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_py", patTau_leadPFChargedHadrCand_py)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_pz", patTau_leadPFChargedHadrCand_pz)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_rapidity", patTau_leadPFChargedHadrCand_rapidity)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_theta", patTau_leadPFChargedHadrCand_theta)
stream.select("patTauHelper_patTaus.leadPFChargedHadrCand_y", patTau_leadPFChargedHadrCand_y)
stream.select("patTauHelper_patTaus.p", patTau_p)
stream.select("patTauHelper_patTaus.phi", patTau_phi)
stream.select("patTauHelper_patTaus.pt", patTau_pt)
stream.select("patTauHelper_patTaus.px", patTau_px)
stream.select("patTauHelper_patTaus.py", patTau_py)
stream.select("patTauHelper_patTaus.pz", patTau_pz)
stream.select("patTauHelper_patTaus.tauID_againstElectronDeadECAL", patTau_tauID_againstElectronDeadECAL)
stream.select("patTauHelper_patTaus.tauID_againstElectronLoose", patTau_tauID_againstElectronLoose)
stream.select("patTauHelper_patTaus.tauID_againstElectronLooseMVA5", patTau_tauID_againstElectronLooseMVA5)
stream.select("patTauHelper_patTaus.tauID_againstElectronMVA5category", patTau_tauID_againstElectronMVA5category)
stream.select("patTauHelper_patTaus.tauID_againstElectronMVA5raw", patTau_tauID_againstElectronMVA5raw)
stream.select("patTauHelper_patTaus.tauID_againstElectronMedium", patTau_tauID_againstElectronMedium)
stream.select("patTauHelper_patTaus.tauID_againstElectronMediumMVA5", patTau_tauID_againstElectronMediumMVA5)
stream.select("patTauHelper_patTaus.tauID_againstElectronTight", patTau_tauID_againstElectronTight)
stream.select("patTauHelper_patTaus.tauID_againstElectronTightMVA5", patTau_tauID_againstElectronTightMVA5)
stream.select("patTauHelper_patTaus.tauID_againstElectronVLooseMVA5", patTau_tauID_againstElectronVLooseMVA5)
stream.select("patTauHelper_patTaus.tauID_againstElectronVTightMVA5", patTau_tauID_againstElectronVTightMVA5)
stream.select("patTauHelper_patTaus.tauID_againstMuonLoose", patTau_tauID_againstMuonLoose)
stream.select("patTauHelper_patTaus.tauID_againstMuonLoose2", patTau_tauID_againstMuonLoose2)
stream.select("patTauHelper_patTaus.tauID_againstMuonLoose3", patTau_tauID_againstMuonLoose3)
stream.select("patTauHelper_patTaus.tauID_againstMuonLooseMVA", patTau_tauID_againstMuonLooseMVA)
stream.select("patTauHelper_patTaus.tauID_againstMuonMVAraw", patTau_tauID_againstMuonMVAraw)
stream.select("patTauHelper_patTaus.tauID_againstMuonMedium", patTau_tauID_againstMuonMedium)
stream.select("patTauHelper_patTaus.tauID_againstMuonMedium2", patTau_tauID_againstMuonMedium2)
stream.select("patTauHelper_patTaus.tauID_againstMuonMediumMVA", patTau_tauID_againstMuonMediumMVA)
stream.select("patTauHelper_patTaus.tauID_againstMuonTight", patTau_tauID_againstMuonTight)
stream.select("patTauHelper_patTaus.tauID_againstMuonTight2", patTau_tauID_againstMuonTight2)
stream.select("patTauHelper_patTaus.tauID_againstMuonTight3", patTau_tauID_againstMuonTight3)
stream.select("patTauHelper_patTaus.tauID_againstMuonTightMVA", patTau_tauID_againstMuonTightMVA)
stream.select("patTauHelper_patTaus.tauID_byCombinedIsolationDeltaBetaCorrRaw", patTau_tauID_byCombinedIsolationDeltaBetaCorrRaw)
stream.select("patTauHelper_patTaus.tauID_byCombinedIsolationDeltaBetaCorrRaw3Hits", patTau_tauID_byCombinedIsolationDeltaBetaCorrRaw3Hits)
stream.select("patTauHelper_patTaus.tauID_byIsolationMVA3newDMwLTraw", patTau_tauID_byIsolationMVA3newDMwLTraw)
stream.select("patTauHelper_patTaus.tauID_byIsolationMVA3newDMwoLTraw", patTau_tauID_byIsolationMVA3newDMwoLTraw)
stream.select("patTauHelper_patTaus.tauID_byIsolationMVA3oldDMwLTraw", patTau_tauID_byIsolationMVA3oldDMwLTraw)
stream.select("patTauHelper_patTaus.tauID_byIsolationMVA3oldDMwoLTraw", patTau_tauID_byIsolationMVA3oldDMwoLTraw)
stream.select("patTauHelper_patTaus.tauID_byLooseCombinedIsolationDeltaBetaCorr", patTau_tauID_byLooseCombinedIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byLooseCombinedIsolationDeltaBetaCorr3Hits", patTau_tauID_byLooseCombinedIsolationDeltaBetaCorr3Hits)
stream.select("patTauHelper_patTaus.tauID_byLooseIsolation", patTau_tauID_byLooseIsolation)
stream.select("patTauHelper_patTaus.tauID_byLooseIsolationMVA3newDMwLT", patTau_tauID_byLooseIsolationMVA3newDMwLT)
stream.select("patTauHelper_patTaus.tauID_byLooseIsolationMVA3newDMwoLT", patTau_tauID_byLooseIsolationMVA3newDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byLooseIsolationMVA3oldDMwLT", patTau_tauID_byLooseIsolationMVA3oldDMwLT)
stream.select("patTauHelper_patTaus.tauID_byLooseIsolationMVA3oldDMwoLT", patTau_tauID_byLooseIsolationMVA3oldDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byMediumCombinedIsolationDeltaBetaCorr", patTau_tauID_byMediumCombinedIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byMediumCombinedIsolationDeltaBetaCorr3Hits", patTau_tauID_byMediumCombinedIsolationDeltaBetaCorr3Hits)
stream.select("patTauHelper_patTaus.tauID_byMediumIsolationMVA3newDMwLT", patTau_tauID_byMediumIsolationMVA3newDMwLT)
stream.select("patTauHelper_patTaus.tauID_byMediumIsolationMVA3newDMwoLT", patTau_tauID_byMediumIsolationMVA3newDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byMediumIsolationMVA3oldDMwLT", patTau_tauID_byMediumIsolationMVA3oldDMwLT)
stream.select("patTauHelper_patTaus.tauID_byMediumIsolationMVA3oldDMwoLT", patTau_tauID_byMediumIsolationMVA3oldDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byTightCombinedIsolationDeltaBetaCorr", patTau_tauID_byTightCombinedIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byTightCombinedIsolationDeltaBetaCorr3Hits", patTau_tauID_byTightCombinedIsolationDeltaBetaCorr3Hits)
stream.select("patTauHelper_patTaus.tauID_byTightIsolationMVA3newDMwLT", patTau_tauID_byTightIsolationMVA3newDMwLT)
stream.select("patTauHelper_patTaus.tauID_byTightIsolationMVA3newDMwoLT", patTau_tauID_byTightIsolationMVA3newDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byTightIsolationMVA3oldDMwLT", patTau_tauID_byTightIsolationMVA3oldDMwLT)
stream.select("patTauHelper_patTaus.tauID_byTightIsolationMVA3oldDMwoLT", patTau_tauID_byTightIsolationMVA3oldDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byVLooseCombinedIsolationDeltaBetaCorr", patTau_tauID_byVLooseCombinedIsolationDeltaBetaCorr)
stream.select("patTauHelper_patTaus.tauID_byVLooseIsolationMVA3newDMwLT", patTau_tauID_byVLooseIsolationMVA3newDMwLT)
stream.select("patTauHelper_patTaus.tauID_byVLooseIsolationMVA3newDMwoLT", patTau_tauID_byVLooseIsolationMVA3newDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byVLooseIsolationMVA3oldDMwLT", patTau_tauID_byVLooseIsolationMVA3oldDMwLT)
stream.select("patTauHelper_patTaus.tauID_byVLooseIsolationMVA3oldDMwoLT", patTau_tauID_byVLooseIsolationMVA3oldDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byVTightIsolationMVA3newDMwLT", patTau_tauID_byVTightIsolationMVA3newDMwLT)
stream.select("patTauHelper_patTaus.tauID_byVTightIsolationMVA3newDMwoLT", patTau_tauID_byVTightIsolationMVA3newDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byVTightIsolationMVA3oldDMwLT", patTau_tauID_byVTightIsolationMVA3oldDMwLT)
stream.select("patTauHelper_patTaus.tauID_byVTightIsolationMVA3oldDMwoLT", patTau_tauID_byVTightIsolationMVA3oldDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byVVTightIsolationMVA3newDMwLT", patTau_tauID_byVVTightIsolationMVA3newDMwLT)
stream.select("patTauHelper_patTaus.tauID_byVVTightIsolationMVA3newDMwoLT", patTau_tauID_byVVTightIsolationMVA3newDMwoLT)
stream.select("patTauHelper_patTaus.tauID_byVVTightIsolationMVA3oldDMwLT", patTau_tauID_byVVTightIsolationMVA3oldDMwLT)
stream.select("patTauHelper_patTaus.tauID_byVVTightIsolationMVA3oldDMwoLT", patTau_tauID_byVVTightIsolationMVA3oldDMwoLT)
stream.select("patTauHelper_patTaus.tauID_chargedIsoPtSum", patTau_tauID_chargedIsoPtSum)
stream.select("patTauHelper_patTaus.tauID_decayModeFinding", patTau_tauID_decayModeFinding)
stream.select("patTauHelper_patTaus.tauID_decayModeFindingNewDMs", patTau_tauID_decayModeFindingNewDMs)
stream.select("patTauHelper_patTaus.tauID_decayModeFindingOldDMs", patTau_tauID_decayModeFindingOldDMs)
stream.select("patTauHelper_patTaus.tauID_neutralIsoPtSum", patTau_tauID_neutralIsoPtSum)
stream.select("patTauHelper_patTaus.tauID_puCorrPtSum", patTau_tauID_puCorrPtSum)
stream.select("patTauHelper_patTaus.vx", patTau_vx)
stream.select("patTauHelper_patTaus.vy", patTau_vy)
stream.select("patTauHelper_patTaus.vz", patTau_vz)
stream.select("recoBeamSpot_offlineBeamSpot.x0", recoBeamSpot_x0)
stream.select("recoBeamSpot_offlineBeamSpot.y0", recoBeamSpot_y0)
stream.select("recoBeamSpot_offlineBeamSpot.z0", recoBeamSpot_z0)
stream.select("recoGenParticleHelperPlus_genParticles.charge", recoGenParticleHelperPlus_charge)
stream.select("recoGenParticleHelperPlus_genParticles.eta", recoGenParticleHelperPlus_eta)
stream.select("recoGenParticleHelperPlus_genParticles.firstDaughter", recoGenParticleHelperPlus_firstDaughter)
stream.select("recoGenParticleHelperPlus_genParticles.firstMother", recoGenParticleHelperPlus_firstMother)
stream.select("recoGenParticleHelperPlus_genParticles.lastDaughter", recoGenParticleHelperPlus_lastDaughter)
stream.select("recoGenParticleHelperPlus_genParticles.lastMother", recoGenParticleHelperPlus_lastMother)
stream.select("recoGenParticleHelperPlus_genParticles.mass", recoGenParticleHelperPlus_mass)
stream.select("recoGenParticleHelperPlus_genParticles.pdgId", recoGenParticleHelperPlus_pdgId)
stream.select("recoGenParticleHelperPlus_genParticles.phi", recoGenParticleHelperPlus_phi)
stream.select("recoGenParticleHelperPlus_genParticles.pt", recoGenParticleHelperPlus_pt)
stream.select("recoGenParticleHelperPlus_genParticles.status", recoGenParticleHelperPlus_status)
stream.select("recoGenParticleHelper_genParticles.charge", recoGenParticleHelper_charge)
stream.select("recoGenParticleHelper_genParticles.eta", recoGenParticleHelper_eta)
stream.select("recoGenParticleHelper_genParticles.firstDaughter", recoGenParticleHelper_firstDaughter)
stream.select("recoGenParticleHelper_genParticles.firstMother", recoGenParticleHelper_firstMother)
stream.select("recoGenParticleHelper_genParticles.lastDaughter", recoGenParticleHelper_lastDaughter)
stream.select("recoGenParticleHelper_genParticles.lastMother", recoGenParticleHelper_lastMother)
stream.select("recoGenParticleHelper_genParticles.mass", recoGenParticleHelper_mass)
stream.select("recoGenParticleHelper_genParticles.pdgId", recoGenParticleHelper_pdgId)
stream.select("recoGenParticleHelper_genParticles.phi", recoGenParticleHelper_phi)
stream.select("recoGenParticleHelper_genParticles.pt", recoGenParticleHelper_pt)
stream.select("recoGenParticleHelper_genParticles.status", recoGenParticleHelper_status)
stream.select("recoGsfElectron_gsfElectrons.deltaEtaSuperClusterTrackAtVtx", recoGsfElectron_deltaEtaSuperClusterTrackAtVtx)
stream.select("recoGsfElectron_gsfElectrons.deltaPhiSuperClusterTrackAtVtx", recoGsfElectron_deltaPhiSuperClusterTrackAtVtx)
stream.select("recoGsfElectron_gsfElectrons.dr04EcalRecHitSumEt", recoGsfElectron_dr04EcalRecHitSumEt)
stream.select("recoGsfElectron_gsfElectrons.dr04TkSumPt", recoGsfElectron_dr04TkSumPt)
stream.select("recoGsfElectron_gsfElectrons.eSuperClusterOverP", recoGsfElectron_eSuperClusterOverP)
stream.select("recoGsfElectron_gsfElectrons.energy", recoGsfElectron_energy)
stream.select("recoGsfElectron_gsfElectrons.et", recoGsfElectron_et)
stream.select("recoGsfElectron_gsfElectrons.eta", recoGsfElectron_eta)
stream.select("recoGsfElectron_gsfElectrons.gsfTrack_d0", recoGsfElectron_gsfTrack_d0)
stream.select("recoGsfElectron_gsfElectrons.gsfTrack_dxy", recoGsfElectron_gsfTrack_dxy)
stream.select("recoGsfElectron_gsfElectrons.gsfTrack_dz", recoGsfElectron_gsfTrack_dz)
stream.select("recoGsfElectron_gsfElectrons.hadronicOverEm", recoGsfElectron_hadronicOverEm)
stream.select("recoGsfElectron_gsfElectrons.p", recoGsfElectron_p)
stream.select("recoGsfElectron_gsfElectrons.phi", recoGsfElectron_phi)
stream.select("recoGsfElectron_gsfElectrons.pt", recoGsfElectron_pt)
stream.select("recoGsfElectron_gsfElectrons.px", recoGsfElectron_px)
stream.select("recoGsfElectron_gsfElectrons.py", recoGsfElectron_py)
stream.select("recoGsfElectron_gsfElectrons.pz", recoGsfElectron_pz)
stream.select("recoGsfElectron_gsfElectrons.scE1x5", recoGsfElectron_scE1x5)
stream.select("recoGsfElectron_gsfElectrons.scE2x5Max", recoGsfElectron_scE2x5Max)
stream.select("recoGsfElectron_gsfElectrons.scE5x5", recoGsfElectron_scE5x5)
stream.select("recoGsfElectron_gsfElectrons.sigmaIetaIeta", recoGsfElectron_sigmaIetaIeta)
stream.select("recoPFMET_pfType1p2CorrectedMet.energy", recoPFMET1_energy)
stream.select("recoPFMET_pfType1p2CorrectedMet.et", recoPFMET1_et)
stream.select("recoPFMET_pfType1p2CorrectedMet.eta", recoPFMET1_eta)
stream.select("recoPFMET_pfType1p2CorrectedMet.p", recoPFMET1_p)
stream.select("recoPFMET_pfType1p2CorrectedMet.phi", recoPFMET1_phi)
stream.select("recoPFMET_pfType1p2CorrectedMet.pt", recoPFMET1_pt)
stream.select("recoPFMET_pfType1p2CorrectedMet.px", recoPFMET1_px)
stream.select("recoPFMET_pfType1p2CorrectedMet.py", recoPFMET1_py)
stream.select("recoPFMET_pfType1p2CorrectedMet.pz", recoPFMET1_pz)
stream.select("recoPFMET_pfType1CorrectedMet.energy", recoPFMET_energy)
stream.select("recoPFMET_pfType1CorrectedMet.et", recoPFMET_et)
stream.select("recoPFMET_pfType1CorrectedMet.eta", recoPFMET_eta)
stream.select("recoPFMET_pfType1CorrectedMet.p", recoPFMET_p)
stream.select("recoPFMET_pfType1CorrectedMet.phi", recoPFMET_phi)
stream.select("recoPFMET_pfType1CorrectedMet.pt", recoPFMET_pt)
stream.select("recoPFMET_pfType1CorrectedMet.px", recoPFMET_px)
stream.select("recoPFMET_pfType1CorrectedMet.py", recoPFMET_py)
stream.select("recoPFMET_pfType1CorrectedMet.pz", recoPFMET_pz)
stream.select("recoVertex_offlinePrimaryVertices.isFake", recoVertex_isFake)
stream.select("recoVertex_offlinePrimaryVertices.ndof", recoVertex_ndof)
stream.select("recoVertex_offlinePrimaryVertices.x", recoVertex_x)
stream.select("recoVertex_offlinePrimaryVertices.y", recoVertex_y)
stream.select("recoVertex_offlinePrimaryVertices.z", recoVertex_z)

