/********************************************************************
* src/dictionary.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/dictionary.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledictionary();
extern void G__cpp_setup_inheritancedictionary();
extern void G__cpp_setup_typetabledictionary();
extern void G__cpp_setup_memvardictionary();
extern void G__cpp_setup_globaldictionary();
extern void G__cpp_setup_memfuncdictionary();
extern void G__cpp_setup_funcdictionary();
extern void G__set_cpp_environmentdictionary();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/tnm.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dictionaryLN_vectorlEcharcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlElongcOallocatorlElonggRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEunsignedsPlongcOallocatorlEunsignedsPlonggRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__dictionaryLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__dictionaryLN_string;
extern G__linked_taginfo G__dictionaryLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__dictionaryLN_TFile;
extern G__linked_taginfo G__dictionaryLN_TTree;
extern G__linked_taginfo G__dictionaryLN_TLeaf;
extern G__linked_taginfo G__dictionaryLN_TBranch;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOintcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOintgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOdoublecOlesslEstringgRcOallocatorlEpairlEconstsPstringcOdoublegRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__dictionaryLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__dictionaryLN_TH1F;
extern G__linked_taginfo G__dictionaryLN_TChain;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOFieldcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOFieldgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOFieldmUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOFieldmUgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_itreestream;
extern G__linked_taginfo G__dictionaryLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_vectorlETChainmUcOallocatorlETChainmUgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlETChainmUcOallocatorlETChainmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_otreestream;
extern G__linked_taginfo G__dictionaryLN_vectorlEintmUcOallocatorlEintmUgRsPgR;
extern G__linked_taginfo G__dictionaryLN_reverse_iteratorlEvectorlEintmUcOallocatorlEintmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dictionaryLN_eventBuffer;
extern G__linked_taginfo G__dictionaryLN_maplEstringcOvectorlEintcOallocatorlEintgRsPgRcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOvectorlEintcOallocatorlEintgRsPgRsPgRsPgRsPgR;
extern G__linked_taginfo G__dictionaryLN_outputFile;
extern G__linked_taginfo G__dictionaryLN_commandLine;
extern G__linked_taginfo G__dictionaryLN_matchedPair;
extern G__linked_taginfo G__dictionaryLN_ptThing;

/* STUB derived class for protected member access */
